### ISSUE TITLE
[question]do I need to declare a pool when producing messages in kafka

### ISSUE THREAD

**Issue by jamky** [segmentio/kafka-go#1048]
#### I am a novice to the go language,I wonder if I need to declare a pool when producing messages in kafka? like this
```
var kafkaWriterPool = sync.Pool{
	New: func() interface{} {
		return &kafka.Writer{
			Addr:     kafka.TCP("kafka_host"),
			Topic:    "kafka_topic",
			Balancer: &kafka.LeastBytes{},
		}
	},
}
func KafkaProduce(key, value string) error {
	kafkaWriter := kafkaWriterPool.Get().(*kafka.Writer)
	defer kafkaWriterPool.Put(kafkaWriter)
	msg := kafka.Message{
		Key:   []byte(key),
		Value: []byte(value),
	}
	err := kafkaWriter.WriteMessages(context.Background(), msg)
	if err != nil {
		fmt.Printf("[Kafka]failed to produce message,key=%s, error: %s\n", key, err.Error())
		return err
	}
	fmt.Printf("[Kafka]produce message successfully,key=%s\n", key)
	return nil
}
```

**Comment by dominicbarnes** [comment]
Much of the time, applications will include `*kafka.Writer` as a member of some sort of shared worker struct (or maybe as a global variable) rather than using a pool like this, though there isn't anything _wrong_ with doing this, I suspect it may be over-engineered compared to simpler alternatives.

I'm going to close this issue, but if you have additional details about your use-case that we can dig into further, feel free to re-open.
