### ISSUE TITLE
Question: why implement `batchQueue` as a concurrency slice instead of use channel directly ?

### ISSUE THREAD

**Issue by 3AceShowHand** [segmentio/kafka-go#1058]
#716 introduce the `batchQueue`, which is implemented as a concurrent `slice of writeBatch`.

By my observation, it can be simply replaced by `channel of writeBatch`.

Is there anyone can help me figure out why not use the channel here?

**Comment by rhansen2** [comment]
Hi @3AceShowHand,

The main reason a channel wasn't used here is that as far as I'm aware there is no guaranteed order for goroutines to unblock when multiple are blocked on a channel send. Since our reason for these changes was to guarantee ordering a slice seemed like the right choice.

Hopefully that make sense, Thanks!
