### ISSUE TITLE
reader.CommitMessages()

### ISSUE THREAD

**Issue by mahditakrim** [segmentio/kafka-go#1080]
reader.CommitMessages() can get multiple messages to commit, but when Kafka commits an offset it also commits all previous offsets, so it's kind of nonsense that CommitMessages() can get multiple messages with different offsets to commit.
My question is what is the benefit of giving multiple messages to CommitMessages() ?

**Comment by dominicbarnes** [comment]
The API here allows you to blindly pass your messages to `CommitMessages`, and it will take care of the book-keeping for you. You can also pass messages across multiple topics/partitions, so this aids in that as well.

All in all, it's meant to be a helper API. I'll close the issue since I've provided an answer, but feel free to re-open if you have follow-ups.

**Comment by mahditakrim** [comment]
> The API here allows you to blindly pass your messages to `CommitMessages`, and it will take care of the book-keeping for you. You can also pass messages across multiple topics/partitions, so this aids in that as well.
> 
> All in all, it's meant to be a helper API. I'll close the issue since I've provided an answer, but feel free to re-open if you have follow-ups.

Thanks for your response, but I have to mention that CommitMessages() should have more clear comment to illustrate the exact functionality.
