### ISSUE TITLE
writer's `batchTime` metrics is inaccurate

### ISSUE THREAD

**Issue by 3AceShowHand** [segmentio/kafka-go#1101]
**Describe the bug**

> A clear and concise description of what the bug is.

* batchTime records the time cost of batch messages. 

Each batch is queued and then waits to be consumed. At the moment, the `batchTime` is reported after it's consumed, instead of the batching is finished, so the metrics is inaccurate.

**Kafka Version**

> * What version(s) of Kafka are you testing against?
> * What version of kafka-go are you using?

**To Reproduce**

> Resources to reproduce the behavior:

```yaml
---
# docker-compose.yaml
#
# Adding a docker-compose file will help the maintainers setup the environment
# to reproduce the issue.
#
# If one the docker-compose files available in the repository may be used,
# mentioning it is also a useful alternative.
...
```

```go
package main

import (
    "github.com/segmentio/kafka-go"
)

func main() {
    // Adding a fully reproducible example will help maintainers provide
    // assistance to debug the issues.
    ...
}
```

**Expected Behavior**

> A clear and concise description of what you expected to happen.

**Observed Behavior**

> A clear and concise description of the behavior you observed.

```
Often times, pasting the logging output from a kafka.Reader or kafka.Writer will
provide useful details to help maintainers investigate the issue and provide a
fix. If possible, providing stack traces or CPU/memory profiles may also contain
valuable information to understand the conditions that triggered the issue.
```

**Additional Context**

> Add any other context about the problem here.

**Comment by 3AceShowHand** [comment]
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/7138436/227447972-cf3985c6-4171-45b3-9492-2d4f3f7dfc3a.png">

This is our monitoring, the batch duration goes up to around 2 seconds at the most, but we set the `BatchTimeout` to 5ms, so the metric is inaccurate.

**Comment by dominicbarnes** [comment]
I see what you are saying, but I also noticed there are currently no comments that describe what these metrics are semantically, so this could be up for interpretation.

Rather than changing the current semantics, would you be opposed to adding a new metric to cover this specifically?

I feel like `batchTime` can continue to refer to the total duration between messages being queued into a batch through when the batch is written. (no change)

We can add a new duration metric (eg: `batchQueueTime`) which will specifically refer to the time taken for messages to be collected into a batch.

**Comment by dominicbarnes** [comment]
I'm going to close this ticket due to a lack of activity. We will still consider a PR to address this, leaning heavily into adding new metrics that have clearly defined semantics rather than altering existing ones.
