### ISSUE TITLE
No error message on non-existent topic

### ISSUE THREAD

**Issue by kostiamol** [segmentio/kafka-go#1142]
Using non-existent topic doesn't issue an error neither during reader creation nor on message reading:

kafka-go  v0.4.40

```
func main() {
	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:   []string{"broker1", "broker2},
		Topic:     "random_topic",
		Partition: 0,
		GroupID:   "gid",
		MinBytes:  10e3,
		MaxBytes:  10e6, 
	})

	for {
		m, err := r.ReadMessage(context.Background())
		if err != nil {
			break
		}
		fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
		time.Sleep(2 * time.Second)
	}

	if err := r.Close(); err != nil {
		log.Fatal("failed to close reader:", err)
	}
}
```

**Comment by moogacs** [comment]
i think that's not a bug, it's an expected behaviour, because it will wait until the topic gets created. so technically it's not a bug.

I would suggest using [`topics.List(..)`](https://github.com/segmentio/kafka-go/blob/ce799ad1e8b5daaa6f72c094330c190d3733366e/topics/list_topics.go#L15)  to list all the existed topics and then check if the one you want to read from them is in or not before configuring the read if that's convenient for your impl. 

something like 
```go
existedTopics, err := topics.List(ctx, client)
if err != nil {
  return err // or exit
}

if !isTopicIn(myTopic, existedTopics){
  return err // or exit
}

```

**Comment by kostiamol** [comment]
@moogacs the trouble is that I have multiple kafka readers under the same consumer group id. And if the topic doesn't exist for at least one reader - all readers are blocked. So the only way to fix that is to validate the topics before start the readers?

**Comment by moogacs** [comment]
yes, they will be all waiting until the topic is created, so as convenient solution now would be check the optic before creating the reader will do

**Comment by kostiamol** [comment]
@moogacs thanks!

**Comment by Abdulsametileri** [comment]
@moogacs what about, how can I check I can consume/produce a specified topic? 🙏🏻

**Comment by Abdulsametileri** [comment]
@achille-roussel @dominicbarnes @rhansen2 Can I get your comments on this issue? 🤔
