### ISSUE TITLE
what if I use both async and RequiredAcks for Writer?

### ISSUE THREAD

**Issue by DiveInto** [segmentio/kafka-go#119]
```go
	WebsocketKafkaWriter = kafka.NewWriter(kafka.WriterConfig{
		...
                 ...
		
                 RequiredAcks: -1,
		Async:        true,
	})
```

will config like this make Writer async(batch sending the messages), and at the same time, when sending the messages, all the msgs need ack from all replicas?

**Comment by achille-roussel** [comment]
So you are configuring the writer to produce asynchronously? If that's the case then it is a lossy writer, which is why the option is disabled by default. Even with required acks, the writer may fail to send the messages and give them up.

The fact that it happens after long period of inactivities may indicate the it can be related to idle connections timing out and the client not detecting it, we could investigate whether that's the case but ultimately using an async writer means that the application should tolerate message loss.

Would you be able to use a synchronous writer to verify whether you still observe the issue?

**Comment by DiveInto** [comment]
Yes, it's a asyn-producer and its caused by idle connections timing out.

any suggestion to get rid of the message loss caused by this? 
the pattern is that if client idle for some time, it will fail to deliver the 1st msg, then follow up msgs will success.

One solution I can come up with is starting a go routine, and periodically send msgs to keep the producer alive.

Don't know if there is any build-in config to keep the producer alive.

**Comment by stevevls** [comment]
Closing this issue since it sounds like the code is behaving as documented and there's a possible workaround.
