### ISSUE TITLE
Invalid Codec error: running Consumer

### ISSUE THREAD

**Issue by mr-woot** [segmentio/kafka-go#161]
When I try to run consumer, it throws error as "invalid codec"

```
package main

import "fmt"
import "time"
import "context"
import "github.com/segmentio/kafka-go-master"

func main() {
// to consume messages
topic := "test-topic"
partition := 0

conn, _ := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topic, partition)

conn.SetReadDeadline(time.Now().Add(10*time.Second))
batch := conn.ReadBatch(1, 1e6) // fetch 10KB min, 1MB max

b := make([] byte, 1) // 10KB max per message
for {
    _, err := batch.Read(b)
    if err != nil {
        fmt.Println(err)
        break
    }
    fmt.Println(string(b))
}

batch.Close()
conn.Close()
}

```

**Comment by stevevls** [comment]
It looks to me like you're reading compressed messages, but kafka-go hasn't been configured for that.  In order to keep required dependencies to a minimum, we doesn't automatically pull in all of the compression codecs.  Each codec lives in its own subpackage, and it's up to the client to import the codecs they will require.  If you known which compression format is in use, you can import it explicitly.  For example, if you're using Snappy, then adding this import will fix your issue:

```
import _ "github.com/segmentio/kafka-go/snappy"
```

If you don't know which codec you need, or if you want to support all compression formats, you can import them all.  We currently support `gzip`, `snappy`, and `lz4`.

Hope that helps!

**Comment by bullsi** [comment]
@stevevls Thank you, that works. However, I am facing another issue. Since I wanted to use consumer group Id, I used `kafka.NewReader` as below. It works all fine except that it takes considerable seconds (sometimes 10s) to actually consume from Kafka. It's counterpart written in Python consumes the messages immediately. 

```
r := kafka.NewReader(kafka.ReaderConfig{
        Brokers:   []string{"10.120.0.6:9092"},
        GroupID:   "testgroup1",
        Topic:     "com",
        Partition: 0,
    })
    
    for {
        m, err := r.ReadMessage(context.Background())
        if err != nil {
            fmt.Println(err)
            break
        }
        fmt.Println(m.Time)
        fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
    }
```

**Comment by bullsi** [comment]
@stevevls Thank you, that works. However, I am facing another issue. Since I wanted to use consumer group Id, I used `kafka.NewReader` as below. It works all fine except that it takes considerable seconds (sometimes 10s) to actually consume from Kafka. It's counterpart written in Python consumes the messages immediately. 

```
r := kafka.NewReader(kafka.ReaderConfig{
        Brokers:   []string{"10.120.0.6:9092"},
        GroupID:   "testgroup1",
        Topic:     "com",
        Partition: 0,
    })
    
    for {
        m, err := r.ReadMessage(context.Background())
        if err != nil {
            fmt.Println(err)
            break
        }
        fmt.Println(m.Time)
        fmt.Printf("message at offset %d: %s = %s\n", m.Offset, string(m.Key), string(m.Value))
    }
```

**Comment by mr-woot** [comment]
@stevevls It worked.

**Comment by achille-roussel** [comment]
@mr-woot should we close this issue?

**Comment by mr-woot** [comment]
> @mr-woot should we close this issue?

yes.
