### ISSUE TITLE
The leaveGroup is not called on close

### ISSUE THREAD

**Issue by ppatierno** [segmentio/kafka-go#164]
I have a simple consumer application which uses the blocking `ReadMessage` in an infinite for loop for getting messages.
In order to close the consumer gracefully I am using a context with "cancel" ...

```
ctx, cancel := context.WithCancel(context.Background())
```

There is a go routine which is in charge to get signals (SIGING, SIGKILL, ...) and calling the above `cancel` function in order to have the main routine exiting from the blocking `ReadMessage`.

After that I call the `close` on the reader.
What I see from the Kafka broker log but even using Wireshark is that the leave group message is not sent by the reader when the application calls `close`.
Is this pattern the right way? Or cancelling the context corrupts something so that it's normal that the `close` doesn't call the `leaveGroup`? What's the right way to do it? 

From the doc it seems I am on the right way because is says "... and exposes an API that supports asynchronous cancellations and timeouts using Go contexts"

I also tried to call the `close` just after receiving a message (inside the for loop) in order to avoid using canceling the context but it's the same, no `leaveGroup` is called.

**Comment by ppatierno** [comment]
I don't know the library in details (I should dig into the code) but if "reader is closed" means that the consumer has closed the connection to the brokers, then it will start a partitions rebalancing in the consumer group. The clean way should be having the consumer sending the "leave group" while it's still connected.

**Comment by WillAbides** [comment]
I've recently run into this issue after moving from confluent-kafka-go.

This code in `reader.Close()` confused me:  https://github.com/segmentio/kafka-go/blob/e442c3981eae27aa4da0fa4d7d31d17d0d9721de/reader.go#L1157-L1168

From what I can tell, `r.coordinator()` on line 1164 will always return an error because `r.stctx` will have been canceled by the `r.stop()` on line 1158.  Since `r.coordinator()` is always returning an error, there is no condition where `r.leaveGroup()` is executed.  So the whole block starting on line 1161 is essentially a noop (except for unsuccessfully attempting to dial the leader).

That block could be moved above `r.cancel()` so it works as it was apparently intended, or be removed entirely so it doesn't confuse people like me into thinking that leaveGroup is called on Close.

If @achille-roussel is correct, and it isn't always desirable to leave the group on Close, then there should still be a way to call `leaveGroup()`.  Either by exposing it or by adding `LeaveConsumerGroupOnClose` to ReaderConfig.
