### ISSUE TITLE
kafka.Message to JSON String conversion.

### ISSUE THREAD

**Issue by mr-woot** [segmentio/kafka-go#179]
Hi, any method to convert kafka.Message to JSON string, including values like Topic, Offset, Partition, Value, etc.

**Comment by achille-roussel** [comment]
In go you can marshal any value to JSON with code like this:
```go
b, _ := json.Marshal(msg)
```
The key and value of the message will be base64 encoded because they are `[]byte` value, the rest of the values should be rendered as numbers and strings.

Lett me know if that helped, or maybe you can share a bit more about your use case?

**Comment by mr-woot** [comment]
@achille-roussel You can close this issue.
