### ISSUE TITLE
ReadMessage do not return "invalid codec" error

### ISSUE THREAD

**Issue by abonec** [segmentio/kafka-go#198]
When calling ReadMessage if codec is not imported this method will infinite block with cpu and memory usage. I spent many hours to investigate such kind of problem, it is not user friendly.

**Comment by magicdvd** [comment]
I have the same problem. How could i imported the right codec while ReadMessage?

**Comment by magicdvd** [comment]
I have found the solution 
import codec in main
import _ "github.com/segmentio/kafka-go/snappy"

**Comment by stevevls** [comment]
Glad you found the solution!  I still think that there are two things to fix here:
1. The README talks about how to enable compression on the `Writer` but doesn't have an example for the `Reader`.
1. We should bubble up the error somehow instead of just swallowing it because the `Reader` will not be able to make forward progress in this case.  That's why you end up in the loop.
