### ISSUE TITLE
Asynchronous message processing support

### ISSUE THREAD

**Issue by eliaslevy** [segmentio/kafka-go#202]
When using a `Reader` to process multiple messages concurrently, whether by sharing the `Reader` among a group of goroutines or having main goroutine own the `Reader` that farms out the messages to the worker goroutines, message may finish processing out of order.

Currently, `CommitMessages` assumes that messages are processed in order within a partition, as `offsetStash` merely keeps track of a single offset per partition and `offsetStash.merge` overwrites this value with the offset being committed if it is larger than the current value.  This results in the committed offset advancing even if there are messages with a lower offset still being processed.

The desired behavior is for the committed offset to only advance if all offsets lower than it have been processed. To do so it is necessary to maintain a sorted list per partition of offsets committed by the application but that haven't been committed to the cluster yet, and to only commit the maximum offset in the list that can be reached without any gaps (i.e. the maximum contiguous offset).

**Comment by joshwget** [comment]
What you're suggesting could be built on top of kafka-go rather than directly inside the project. I don't directly work on kafka-go but it seems to me that the goal of the project is to be a low level interface to Kafka (similar to https://github.com/Shopify/sarama).

For our needs we've built a package on top of sarama that supports parallel / out of order processing of messages. Only the "lowest" messages are committed after they've been processed. We could probably open source this code and then it could be ported to kafka-go instead of sarama.

**Comment by stevevls** [comment]
Thanks!  We're not planning on implementing this feature right now.

**Comment by nitin302** [comment]
@joshwget was any of the custom code that you mention, open-sourced?

**Comment by anandsinghkunwar** [comment]
This does seem like a desirable feature to us as well, @achille-roussel will you be willing to accept a PR(can't commit 100% right now) if I add this mode in `kafka-go`?

**Comment by sghosh-discovery** [comment]
Hi, 

was this added in `kafka-go`?
