### ISSUE TITLE
Endless waiting for consumer connection

### ISSUE THREAD

**Issue by pshopper** [segmentio/kafka-go#227]
**Describe the bug**
If kafka unavailable (connection refused or other error), refreshCoordinator func performs endless.

**To Reproduce**
Try to fetch message (by reader.FetchMessage with consumer group) with unavailable kafka.

**Expected behavior**
Reader will return error and logging this.

**Comment by reprah** [comment]
@achille-roussel I'm interested in helping with this issue. If we just want to log that we got a dial timeout, we could log the error inside `refreshCoordinator()` [here](https://github.com/segmentio/kafka-go/blob/3a0e564053e187bc9c18a4e69966d89a4fd4499a/reader.go#L161) and perhaps return the error instead of continuing to the next iteration of the loop. Thoughts?

**Comment by achille-roussel** [comment]
@reprah thanks for offering to help.

Logging the error seems like a good first step, let me know if you're available to make the change 👍

**Comment by alamages** [comment]
Hello,

I see the code has change quite a bit since this issue was reported but I would like to mention that this is still an issue.

This is now [the line that causes the problem](https://github.com/segmentio/kafka-go/blob/48f0c131b6a036cfeff519cc8d6ff09de3141d9e/consumergroup.go#L576). The `nextGeneration` function returns an error if a connection can not be established successfully (e.g invalid hostname, wrong port, wrong credentials etc). The error is not really handled but instead is ignored and the for{} loop will try after some "backoff" time again, infinitely. 

The only way to figure out whether there is an error is to pass an error logger in the reader config and look at the logs. This might be good for now but I would expect the consumer to fail if a connection can not be established due to invalid configuration.

Cheers!

**Comment by xiaopeifeng** [comment]
what's the PR status now?

**Comment by stevevls** [comment]
This should be fixed on `master` now thanks to #430 .
