### ISSUE TITLE
write msg to kafka, it take very long time

### ISSUE THREAD

**Issue by chainarong-Trainapakul** [segmentio/kafka-go#248]
// my example code
```go
func main() {
	topic := "myTopic"
	bootstrapServer := "mybootstrapServer "
	w := NewSender(topic, bootstrapServer)
	start := time.Now()
	for i := 0 ; i < 10 ; i ++ {
		err := w.kafkaProducer("msg")
		if err != nil {
			fmt.Println("error:", err)
		}
	}
	elapsed := time.Now().Sub(start)
	fmt.Println(elapsed)
}

func(s *sender) kafkaProducer(msg string) error {
	s.writer.WriteMessages(context.Background(),
		kafka.Message{
			Value: []byte(msg),
		},
	)
	return nil
}

func NewSender(topic string, bootstrapServer string) *sender {
	return &sender{
			writer: kafka.NewWriter(kafka.WriterConfig{
					Brokers: []string{bootstrapServer},
					Topic:   topic,
					Balancer: &kafka.LeastBytes{},
			}),
			context: context.Background(),
	}		
}

type sender struct {
	writer	*kafka.Writer
	context	context.Context
}
```
total time = 10.037994611s
how to write msg quicker than this ?

**Comment by chainarong-Trainapakul** [comment]
kafka version : 2.11-2.1.0

**Comment by achille-roussel** [comment]
The writer will attempt to write messages in batches to be more efficient, this means that each WriteMessages call will block until the message has been sent to Kafka. By default the batch aggregation time is 1s, so that's how long the method will wait at most.

Your example publishes messages 1 at a time, if you published them all 10 in a single WriteMessages call it would take only 1s.

You can also tune the batch wait time on the writer config, or enable asynchronous writes to avoid waiting for the messages to be published.

**Comment by chainarong-Trainapakul** [comment]
small batchTimeOut that's great. 
thank you so much bro!
