### ISSUE TITLE
Reader Error Handling And delay in reading

### ISSUE THREAD

**Issue by arunvinam** [segmentio/kafka-go#252]
Hello,

This is my basic code for reading messages:-
```
func main() {
	reader := kafka.NewReader(kafka.ReaderConfig{
		Brokers: []string{"localhost:9092"},
		GroupID: "sample",
		Topic:   "test_topic",		
	})
	for {
		m, err := reader.ReadMessage(context.Background())
		if err != nil {
			continue
		}
		//time.Sleep(1 * time.Second)
		fmt.Printf("P/O: %v/%v; %v: %v\n", m.Partition, m.Offset, string(m.Key), string(m.Value))

		reader.CommitMessages(context.Background(), m)
	}
}
```
I have two issues here:-

1 .If  kafka.NewReader config is wrong (for eg wrong server or port or server down) it doesn't throw any error as it return a single value(unlike kafka.DialLeader). Is there a way to handle error here?

2. It takes around 3-4 secs to read messages even if there are messages in the stream.  Is this the default behavior or shoud I change any config?

Thanks,
Arun

**Comment by stevevls** [comment]
Hi @arunvinam.  

1. This behavior is actually by design.  When you're consuming from a Kafka topic, you're probably going to be opening connections to multiple brokers.  Even if you are only consuming from a single partition, it's possible that the leader for that partition moves about.  As such, the `Reader` is designed so that it creates and tears down connections in response to what's going on with the cluster.  One thing you can do if you want to learn about the wrong server or port sooner, is you can adjust the `Dialer` (in order to reduce timeout) or reduce `MaxAttempts`.  After `MaxAttempts` to connect, an error will be returned by `ReadMessage`.

2. There are some options available for you to tweak in order to decrease latency.  You generally want to set `MaxWait`, `MinBytes`, and `MaxBytes`.  The defaults are `10s`, `1MB`, and `1MB` respectively.  That means, the fetch request won't return until either 10 seconds pass or you have 1MB worth of data.

Also, note that if you are using `ReadMessage`, there's no need to call `CommitMessages` as that's called automatically.  If you wish to manually commit messages, you should use `FetchMessage` instead of `ReadMessage`.

Thanks!
