### ISSUE TITLE
Received messages don't have any Headers

### ISSUE THREAD

**Issue by vangent** [segmentio/kafka-go#254]
**Describe the bug**
Messages received through `Reader` don't have any `Headers`.

**Kafka Version**
`0.10.1.0` (via https://github.com/spotify/docker-kafka)

**To Reproduce**
1. `docker run -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=localhost spotify/kafka`
2. Run some code something like this:

```
ctx := context.Background()
w := kafka.NewWriter(kafka.WriterConfig{
         Brokers: []string{"localhost:9092"},
         Topic:   "topic",
})
msg := kafka.Message{
    Value: []byte("hello world"),
    Headers: []kafka.Header{kafka.Header{Key: "foo", Value: []byte("bar")}},
}
if err := w.WriteMessages(ctx, msg); err != nil {
   log.Fatal(err)
}
r := kafka.NewReader(kafka.ReaderConfig{
    Brokers: []string{"localhost:9092"},
    Topic:   "topic",
})
if m, err := r.FetchMessage(ctx); err != nil {
    log.Fatal(err)
} else {
    fmt.Printf("Received message with %d headers\n", len(m.Headers))
}
```
    
**Expected behavior**
Headers that were written via `WriteMessages` should be read via `FetchMessage`.

**Additional context**
Headers were added to `Message` #163, but at least at first glance it looks like it only added it for writing.

**Comment by vangent** [comment]
Hmm, is this because headers are only in 0.11.x?

**Comment by stevevls** [comment]
Hi @vangent.  Message headers were added to Kafka in version `0.11.0` as part of this KIP: https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers.  When talking to Kafka `0.10.1.0`, kafka-go won't try to write the headers because the protocol doesn't allow for it.  We could potentially return an error instead of silently dropping the headers, but there's unfortunately nothing we can do to make them work with that version of Kafka.

**Comment by vangent** [comment]
OK, thanks. Sorry for the churn, I will try again with a more recent version of Kafka.
