### ISSUE TITLE
Seeing a lot of EOF errors when reading from partitions

### ISSUE THREAD

**Issue by ch3fk0ch** [segmentio/kafka-go#258]
Hi, I see in the error logs a lot of messages like

`reader.go:1837: the kafka reader got an unknown error reading partition 13 of presence at offset 20067939: EOF`

is this expected if there are no new messages to consume? Is the EOF coming from kafka? I don't see anything suspicious in the kafka logs.

Kafka version is 2.11-2.0.1

Thanks, Andreas

**Comment by achille-roussel** [comment]
The client code in kafka-go uses connection pooling, so it may happen that a Kafka broker closes a connection if its idle timeout is higher than what the client uses. The client should handle this cases automatically and reconnect to the broker.

Do you happen to know what the idle connection timeouts used on the server side is?

Are you experiencing issues because of this?

**Comment by ch3fk0ch** [comment]
achille, thanks for your response. I don't experience any issues because of this. I was just wondering why it says unknown error. Also this topic is not very busy yet, maybe thats why it always disconnects from the partition.

If you ask about connections.max.idle.ms , it is the default value of 600000. I can try to set a timeout for the client.

**Comment by ch3fk0ch** [comment]
Do you have any suggestion what value I should set to increase the timeout on the client side?

**Comment by achille-roussel** [comment]
The `MaxWait` parameter in the [`ReaderConfig`](https://godoc.org/github.com/segmentio/kafka-go#ReaderConfig) type is what sets how long the client will wait during fetch requests.

It looks like your server is configured to wait long enough tho, I'm not sure if Kafka has other timeouts coming into play here tho.

If this error does not cause any issues we could probably log it with the debug logger instead of the error logger as well.

**Comment by paulqin** [comment]
@achille-roussel

**Comment by paulqin** [comment]
I also dicover this problem this week when we use kafka-go in our product.

**Comment by Knight-Wu** [comment]
hi, i still see a lot of error log : the kafka reader got an unknown error reading partition 0 of... EOF, any suggestions ?

**Comment by isqad** [comment]
Hi, @Knight-Wu! 
I had same problem in my application. 
Could you try set custom Dialer to ReaderConfig with increased KeepAlive timout? https://godoc.org/github.com/segmentio/kafka-go#Dialer

**Comment by shirolimit** [comment]
I think I found the place in code that causes this problem.
Look, when we create a batch to read (https://github.com/segmentio/kafka-go/blob/531c50bb11447b43c02f52718f9213631921fad3/conn.go#L847) we specify `adjustedDeadline` as a `deadline` field of the `Batch` struct.

But it looks like that `adjustedDeadline` is never initialized. So, when we come to the deadline check here (https://github.com/segmentio/kafka-go/blob/531c50bb11447b43c02f52718f9213631921fad3/batch.go#L252) it tells us to fail with `EOF` error.

**Comment by stevevls** [comment]
Nice find on that `adjustedDeadline` is never initialized.  That seems unexpected...

It looks like we're only consulting that value in case of `errShortRead`.  `errShortRead` is a special case that occurs when we didn't read as many bytes as the broker indicated were forthcoming.  To make things interesting, the broker is allowed to do that for a `FetchRequest`.  This case tends to happen when there's a backlog of messages to be consumed because the broker has more messages than fit within the max bytes as requested by the client.  Does that sound like it might apply to your situation?

**Comment by shirolimit** [comment]
@stevevls thank you for the response.

As you said, I got `errShortRead` error which I get a result of a call to `messageSetReaderV2.readHeader()`. It tries to peek the first 8 bytes for the offset, and returns `errShortRead` if there is no data to read.

Here is the trace:
```
github.com/segmentio/kafka-go.peekRead (github.com/segmentio/kafka-go@v0.3.3/read.go:19)
github.com/segmentio/kafka-go.readInt64 (github.com/segmentio/kafka-go@v0.3.3/read.go:42)
github.com/segmentio/kafka-go.(*messageSetReaderV2).readHeader (github.com/segmentio/kafka-go@v0.3.3/message.go:416)
github.com/segmentio/kafka-go.(*messageSetReaderV2).readMessage (github.com/segmentio/kafka-go@v0.3.3/message.go:473)
github.com/segmentio/kafka-go.(*messageSetReader).readMessage (github.com/segmentio/kafka-go@v0.3.3/message.go:130)
github.com/segmentio/kafka-go.(*Batch).readMessage (github.com/segmentio/kafka-go@v0.3.3/batch.go:222)
github.com/segmentio/kafka-go.(*Batch).ReadMessage (github.com/segmentio/kafka-go@v0.3.3/batch.go:178)
github.com/segmentio/kafka-go.(*reader).read (github.com/segmentio/kafka-go@v0.3.3/reader.go:1367)
github.com/segmentio/kafka-go.(*reader).run (github.com/segmentio/kafka-go@v0.3.3/reader.go:1192)
github.com/segmentio/kafka-go.(*Reader).start.func1 (github.com/segmentio/kafka-go@v0.3.3/reader.go:1094)
runtime.goexit
```

It looks like it happens regularly in case when there is no more messages to consume (I actually stumbled upon this problem during integration tests, cause I have only a couple of messages here).

**Comment by stevevls** [comment]
Thanks for the trace...that's really helpful.  I tried to reproduce locally but didn't have any success.  If you're able to repro, would it be possible to capture the bytes for the `FetchResponse` using Wireshark?  Another question: is the topic you're reading from written to by a producer that's using transactions?

What's interesting is that if there were no messages returned, we'd hit this block:
https://github.com/segmentio/kafka-go/blob/master/conn.go#L836.

So we're definitely getting a response that contains some data, it's just incomplete (or more likely we have a bug that makes us think it's incomplete).

**Comment by shirolimit** [comment]
Here is the wireshark dump, containing `FetchRequest` and `FetchResponse`. Wireshark dissector goes crazy about it, saying it is malformed, but he marks all `FetchResponse` like this.

[fetch_request_response.pcapng.gz](https://github.com/segmentio/kafka-go/files/3630819/fetch_request_response.pcapng.gz)

> Another question: is the topic you're reading from written to by a producer that's using transactions?

No transactions, just an ordinary writer, producing one message at the time.

I am still not familiar enough with `kafka-go` internals, but there are some thoughts that might be helpful:
- reader reads messages from the batch in a loop and `batch` uses `messageSetReader` to do the actual read from response payload
- `messageSetReader` uses `messageSetReaderV2.readMessage()` that has an embedded `readerStack` struct that has a field called `remain` - the amount of bytes in a buffer to handle
- `remain` amount is decremented as actual messages are parsed, but even when it becomes `0` we still call `messageSetReaderV2.readMessage()`, trying to read the header and fail with `errShortRead`

**Comment by stevevls** [comment]
Thanks for the wireshark dump.  I ran it through the code, and it did in fact produce the `errShortRead`.  I did some more spelunking, though, and it looks like we've always used `errShortRead` as the mechanism to indicate that there are no more messages in the batch.  In the case of the `messageSetReaderV1`, it's explicit.  In the case of `messageSetReaderV2`, it's a side effect.  Either way, though, it's the correct behavior.  I then went backwards in time looking at diffs and found this: https://github.com/segmentio/kafka-go/pull/277/files#diff-a2ddca1600f34abb91244424f8431c2cL770.  As the author of that PR, I'm a bit embarrassed to say that I don't know why that line went missing. 😬 However, after all that, I don't think that's the real issue!

Picking up the thread about the `errShortRead` as signal for end of batch, it is translated to an `io.EOF` by design to signal the end of the batch.  However, in the reader code, we treat it as an error. https://github.com/segmentio/kafka-go/blob/46a3f299976ec69c3b25526dd0966e185144bbb6/reader.go#L1268-L1274 

In some cases, `io.EOF` is a legitimate error, and the connection should be closed (e.g. the broker may close an idle connection).  However, reading the entire batch successfully should not cause that behavior.  I'm going to open a PR to change how the end of batch is signaled so that it's handled gracefully.  I'll fix the `adjustedDeadline` bit while I'm in there.

**Comment by jcr1984** [comment]
In my case. defer reader.Close() was outside of my go func that contains ReadMessage().
Before:
defer self.reader.Close()
	go func() {
		for self.isRunning {
			message, err := self.reader.ReadMessage(context.Background())

now:
go func() {
		defer self.reader.Close()
		for self.isRunning {
			message, err := self.reader.ReadMessage(context.Background())

And this f** error was gone
