### ISSUE TITLE
Commit Offsets by TopicPartition

### ISSUE THREAD

**Issue by samueltorres** [segmentio/kafka-go#279]
Hi :)

I'm doing a consumer that consumes all that the messages in a parallel fashion with the need for ALO semantics.

I'm following an approach that is similar to [this](https://engineering.sift.com/concurrency-and-at-least-once-semantics-with-the-new-kafka-consumer/#offsetmanager), and I need to completely control the TopicPartition Commit Offsets manually.
Although it is possible to it via the `func (r *Reader) CommitMessages(ctx context.Context, msgs ...Message) error` method, it forces me to store the messages on memory to later on commit them, which is not a very good approach IMO :)

 I would like to have you opinion if we could create a method like `func (r *Reader) CommitOffsets(ctx context.Context, creq CommitOffetsRequests) error` that allows the commits to be done manually without the need to have the messages.

Thanks, 
Amazing Library ❤️

**Comment by stevevls** [comment]
Howdy!  You may be interested in keeping an eye on PR #277.  We're finding more and more that some folks (including ourselves) require a lower-level interface to the consumer group in order to unlock more advanced use cases.  We're wary about loading up more functionality onto the `Reader` type since it's supposed to a) be relatively straightforward and b) work both with and without consumer groups.  Once we finish this PR up, I think it would give you the flexibility to manage your offsets exactly as proposed.

**Comment by samueltorres** [comment]
Nice ! Thanks for the insight 👍
