### ISSUE TITLE
Is there a way to read all messages from a topic without specifying a partition?

### ISSUE THREAD

**Issue by tomklino** [segmentio/kafka-go#291]
I'm trying to read all messages from a topic (specifically __consumer_offsets, so, binary), but unless I check first with `kafkacat` on which partition the messages are, and then create a reader specifically for that partition, I can't read the messages (I'm guessing that if I don't specify a partition it just reads from partition 0?)

Anyway, I was sure partitions should be transparent at the user level, and I would just be able to specify the topic and read/consume all messages from it where the underlying code taking care from which partition to read. Is that not the case?

Is there a way to just read all the messages of a topic from all partitions?

(If there isn't, can this be a feature request?)

**Comment by stevevls** [comment]
Hi @tomklino.  You are correct...if you don't specify a partition, then the default value of zero is used.  The `Reader` can either be used to consume a specific partition or you could use consumer groups to consume in a partition-agnostic manner.  We don't currently have a mode where it consumes all partitions.

Your case is particular, though.  While normally I would steer folks towards consumer groups, that sounds like a recipe for a runaway loop if your consumer were to commit offsets!  You probably _could_ make consumer groups work if you're careful to use `FetchMessage` and not `ReadMessage` since the former doesn't commit offsets.  The safer option would be to use `Conn.ReadPartitions` to discover the number of partitions in the `__consumer_offsets` topic and then open a reader for each.

In the meantime, I'm going to close this issue because we haven't seen a lot of interest in a single reader to consume all partitions since all too frequently there's too much data flowing through a topic for that to be feasible.  Feel free to comment in #150, though, if you really want this feature.  Thanks!

**Comment by d-fal** [comment]
Hi stevevls,

I came across the same thing and I was wondering if it's is possible to consume all of the partitions with only one consumer. I do my best to help with this.
