### ISSUE TITLE
Why write message so slow!

### ISSUE THREAD

**Issue by shukyoo** [segmentio/kafka-go#326]
**Describe the bug**
I compare sarama and kafka-go to write msg.
kafka-go wait about 2 seconds to finish
but sarama finish immediately!
why this so slow!

**this is stat:**
```
	Dials: 1 Writes: 1 Messages: 1 Bytes: 17 Rebalances: 1 Errors: 0 DialTime: {
		Avg: 7.452734 ms Min: 7.452734 ms Max: 7.452734 ms
	}
	WriteTime: {
		Avg: 1.017793708 s Min: 1.017793708 s Max: 1.017793708 s
	}
	WaitTime: {
		Avg: 5.342901 ms Min: 5.342901 ms Max: 5.342901 ms
	}
```

**this is code:**
```go
	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers: []string{"127.0.0.1:1024"},
		Topic:   "test1",
		Balancer: &kafka.LeastBytes{},
	})

	w.WriteMessages(context.Background(),
		kafka.Message{
			Key:   []byte("Key-A"),
			Value: []byte("Hello World!"),
		},
	)

	fmt.Printf("%+v\n", w.Stats())

	w.Close()
```

**Comment by achille-roussel** [comment]
I believe there may be multiple factors that come into play in the example you submitted:

- The default settings are optimized for production workloads where multiple messages are batched together because this is how kafka is commonly used to achieve high throughput and efficient resource usage.

- On the first write, the writer will also have to open connections to the kafka cluster, which will then remain open and be reused for future writes. The connection pooling logic in kafka-go may be using a different strategy which front-loads more work instead of doing things lazily.

My guess is whether you publish 1 or 1000 messages in a single batch, the publish time will be roughly the same.

Would you be able to give more details about the kafka cluster you're using (number of brokers, number of partitions, etc...), as well as explaining your use case a bit more?

If you're looking at reducing the batch timeout in the [WriterConfig](https://godoc.org/github.com/segmentio/kafka-go#WriterConfig), this will reduce the amount time that the writer waits for more data before publishing.

If you wish to never block on writes, you can also configure the writer to work in asynchronous mode.

Let me know if this is helpful!

**Comment by shukyoo** [comment]
I made a batch write test, write msg 100 times
this is code
```go
	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers: []string{"127.0.0.1:1024"},
		Topic:   "test1",
		Balancer: &kafka.LeastBytes{},
	})

	start := time.Now()

	for i:=0; i<100; i++ {
		w.WriteMessages(context.Background(),
			kafka.Message{
				Key:   []byte("Key-A"),
				Value: []byte("Hello World!"),
			},
		)
	}
	w.Close()

	end := time.Now()
	diff := end.Sub(start)
	fmt.Println(diff)
```

it takes: **1m40.3175299s**

Is my test right?

(3brokers, 2partitions, 2replicas)

**Comment by shukyoo** [comment]
this is write on sarama, send msg 100 times
```go
	conf := sarama.NewConfig()
	conf.Producer.Retry.Max = 1
	conf.Producer.RequiredAcks = sarama.WaitForAll
	conf.Producer.Return.Successes = true
	conf.Metadata.Full = true
	conf.Version = sarama.V0_10_0_0
	conf.ClientID = "kafka_test"

	brokers := []string{"10.86.8.210:1024", "10.86.8.210:1025", "10.86.8.210:1026"}
	syncProducer, _ := sarama.NewSyncProducer(brokers, conf)

	start := time.Now()

	for i:=0; i<100; i++ {
		syncProducer.SendMessage(&sarama.ProducerMessage{
			Topic: "test1",
			Value: sarama.StringEncoder("test_message"),
		})
	}

	_ = syncProducer.Close()

	end := time.Now()
	diff := end.Sub(start)
	fmt.Println(diff)
```
it takes: **204.6775ms**

**Comment by achille-roussel** [comment]
The test you showed isn’t a batch test, each message is still published individually by calling WriteMessages in a loop. 

WriteMessages can be passed an arbitrary number of messages which will form a single batch. Try the same test but passing all messages at once to a single call to WriteMessages, or try pushing each message concurrently from different goroutines. 

Like I said, kafka-go’s default settings are optimized for high throughput production workloads. If what you need is low latency on writes then you should lower the batch timeout value. 

Batching is how we get great performance on writes, reads, and compression with kafka. 

If you’re looking to do a meaningful performance analysis of kafka-go and other client libraries, make sure to configure each client with similar settings, otherwise each library may have chosen different defaults that are optimized for different use cases.

**Comment by shukyoo** [comment]
Thanks！If there is a example for batch msg produce in the readme.md it will be helpful for others.

**Comment by achille-roussel** [comment]
> Thanks！If there is a example for batch msg produce in the readme.md it will be helpful for others.

I don't think we have, but we welcome contributions if you want to add this 👍

**Comment by koroky** [comment]
Same issue here, but i think i have figured out the real reason why it so slow.

[Here](https://github.com/segmentio/kafka-go/blob/v0.3.0/writer.go#L361) the code snippet In this method:
`func (w *Writer) WriteMessages(ctx context.Context, msgs ...Message) error {`
```go
timer := time.NewTimer(backoff(attempt+1, 100*time.Millisecond, 1*time.Second))
select {
case <-timer.C:
	// Only clear the error (so we retry the loop) if we have more retries, otherwise
	// we risk silencing the error.
	if attempt < w.config.MaxAttempts-1 {
		err = nil
	}
case <-ctx.Done():
	err = ctx.Err()
case <-w.done:
	err = io.ErrClosedPipe
	}
timer.Stop()
```
The `backoff` returns `time.Second`.
### So every `WriteMessages` has to wait at least one second!!!

@shukyoo That's why **WriteTime** is nearly one second:
```
Avg: 1.017793708 s Min: 1.017793708 s Max: 1.017793708 s
```

**Comment by koroky** [comment]
> I made a batch write test, write msg 100 times
> this is code
> 
> ```go
> 	w := kafka.NewWriter(kafka.WriterConfig{
> 		Brokers: []string{"127.0.0.1:1024"},
> 		Topic:   "test1",
> 		Balancer: &kafka.LeastBytes{},
> 	})
> 
> 	start := time.Now()
> 
> 	for i:=0; i<100; i++ {
> 		w.WriteMessages(context.Background(),
> 			kafka.Message{
> 				Key:   []byte("Key-A"),
> 				Value: []byte("Hello World!"),
> 			},
> 		)
> 	}
> 	w.Close()
> 
> 	end := time.Now()
> 	diff := end.Sub(start)
> 	fmt.Println(diff)
> ```
> 
> it takes: **1m40.3175299s**
> 
> Is my test right?
> 
> (3brokers, 2partitions, 2replicas)

You can set **BatchTimeout** in WriterConfig to avoid long time wait:
```go
    w := kafka.NewWriter(kafka.WriterConfig{
        Brokers:      []string{"localhost:9092"},
        Topic:        "helloworld",
        Balancer:     &kafka.LeastBytes{},
        BatchTimeout: 10 * time.Millisecond,
    }
```

**Comment by arianitu** [comment]
Please create a new method called WriteMessage which uses an internal batch system instead of WriteMessages which you have to create a batch system on top of it.

**Comment by hadrienk** [comment]
I think the `WriteMessages()` method does too much. It is also not clear how it is supposed to be used, even when sending messages in chunks. 

A more sensible approach IMO would be to add new methods as follow: 

```go
// WriteBuffered saves the messages in a buffer, flushing every BufferSize.
// If there's room in the buffer, no message are written. The returned error is the first
// error returned by the Flush method.
func (w *BufferedWriter) WriteBuffered(ctx context.Context, messages ...kafka.Message) error {
	// [...]
}

// Flush sends and then empty the content of the buffer. 
func (w *BufferedWriter) Flush(ctx context.Context) error {
  // [...]
}
```

Building up on the API above, we could add another methods in order to handle timeouts: 

```go
// WriteAndFlushAfter works as WriteBuffered but also calls a Flush with the same context after duration.
func (w *FlushingWriter) WriteBufferedAndFlushAfter(ctx context.Context, delay time.Duration, messages ...kafka.Message) chan error {
  // [...]
}
```

I have working implementation with tests and could contribute if you agree.

**Comment by lovelock** [comment]
> This is a stupid design. WriteMessages should batch internally instead of us having to batch it manually. Intuition would make it seem like you can call WriteMessages in a loop and kafka-go would batch for you and send them out when it received the batch amount or the timeout. This is how all other libraries I've used work.
> 
> Instead, we have to create an entire batching system to call WriteMessages which then batches as well? You might as well remove the entire batch system from this library since you have to create one on top of it.

I am confused by this design too and I run into the **1 second problem** too. If this is the point, I'd choose another library.

**Comment by 82andre** [comment]
The solution is to call WriteMessages by goroutines.
Your code call writer.close then I need use the WaitGroup to wait all productions before close.

In my own code I create the writer once and call the goroutines to WriteMessages, the close is only for gracefully close the app.
Let me know if is ok.

```
func kafkaProducer() {
	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers:  []string{"localhost:9092"},
		Topic:    "testkafkaProducer",
		Balancer: &kafka.LeastBytes{},
	})
	var wg sync.WaitGroup
	start := time.Now()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(idx int, w *kafka.Writer) {
			defer wg.Done()
			err := w.WriteMessages(ctx,
				kafka.Message{
					Key:   []byte("Key-A"),
					Value: []byte("kafkaProducer test " + strconv.Itoa(idx)),
				},
			)
			if err != nil {
				fmt.Println("Error:", err)
			}
		}(i, w)
	}
	wg.Wait()
	w.Close()

	end := time.Now()
	diff := end.Sub(start)
	fmt.Println("diff=", diff)
}
func BenchmarkKafkaProducer(b *testing.B) {
	for i := 0; i < b.N; i++ {
		kafkaProducer()
	}
}
```
for me this run at 1,4s to produce 100 and 2.1s to produce 1000

**Comment by 82andre** [comment]
Best results 
Choose the quantioty (qtt) that you want to test, 
if you put 1 you fall in the realtime problem result in 1s/op then you need change BatchTimeout.

For high values the ns/op result is by qtt:  ns/(op*qtt) = ns by 1 op
My results: 
for qqt = 100
BenchmarkKafkaProducer3-2           2096            598590 ns/op  ==> 598590/100 = 5,98microseconds per message
PASS  ok      iot-handler/internal/interfaces/eventProducer   2.032s
This benchmark generate 100.000 messages per second !!!

for qqt = 1000
BenchmarkKafkaProducer3-2            200           5783224 ns/op  => 5783224 /1000 = 5,78microseconds per message
PASS  ok      iot-handler/internal/interfaces/eventProducer   2.890s


```
func kafkaProducer3(idx int, w *kafka.Writer, wg *sync.WaitGroup, ctx context.Context) {
	defer wg.Done()
	err := w.WriteMessages(ctx,
		kafka.Message{
			Key:   []byte("Key-A"),
			Value: []byte("kafkaProducer test " + strconv.Itoa(idx)),
		},
	)
	if err != nil {
		fmt.Println("Error:", err)
	}
}
func BenchmarkKafkaProducer3(b *testing.B) {
	qtt := 1000 //produce this quantity in test
	w := &kafka.Writer{
		Addr:                   kafka.TCP("localhost:9092"),
		Topic:                  "testkafkaProducer",
		AllowAutoTopicCreation: true,
		Balancer:               &kafka.LeastBytes{},
	}
	var wg sync.WaitGroup

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		for i := 0; i < qtt; i++ {
			wg.Add(1)
			go kafkaProducer3(i, w, &wg, ctx)
		}
		wg.Wait()
	}
	b.StopTimer()
	w.Close()
}
```

**Comment by CrazyCatzzz** [comment]
i have question:
one write has two batch write job,dose that mean second batch job must wait first batch job answer

**Comment by gotostack** [comment]
Meet this issue today, it's Mar 2023 now.

**Comment by joachimbulow** [comment]
May 2023 still seeing this issue - writeMessages from goroutines does not seem to fix the issue, still encountering the problem. k.Writer is a preinitialized writer

### Spinning up a go routines when receiving on channel

```
func publishMessages(messageChannel chan MyMessageStruct, client client.Client) {
	for mess := range messageChannel {
		go func(mess MyMessageStruct) {
			messJson, err := json.Marshal(mess)
			if err != nil {
				logger.ErrorWithMsg("Marshaling of message failed", err)
				return
			}
			client.Publish(src.MY_TOPIC, id, string(messJson))
		}(mess)
	}
}
```

### Writing messages (assumed they would be batched)
```
func (k *KafkaClient) Publish(topic string, key string, message string) error {
	if k.writer == nil {
		k.writer = setupWriter(k)
	}

	err := k.writer.WriteMessages(context.Background(),
		kafka.Message{
			Topic: topic,
			Key:   []byte(key),
			Value: []byte(message),
		},
	)
	if err != nil {
		logger.ErrorWithMsg("Failed to write messages", err)
	}
	return err
}
```

**Comment by joachimbulow** [comment]
I suppose, as was mentioned above, one needs to manually batch messages to pass into the writer.

func (k *KafkaClient) Publish(topic string, key string, message string) error {
	if k.writer == nil {
		k.writer = setupWriter(k)
	}

	err := k.writer.WriteMessages(context.Background(),
		kafka.Message{
			Topic: topic,
			Key:   []byte(key),
			Value: []byte(message),
		},
	)
	if err != nil {
		logger.ErrorWithMsg("Failed to write messages", err)
	}
	return err
}

Really awful design, think we will have to change library.
