### ISSUE TITLE
Support consumer group reset offset manually

### ISSUE THREAD

**Issue by ziwenxie** [segmentio/kafka-go#351]
[just like this gist](https://gist.github.com/marwei/cd40657c481f94ebe273ecc16601674b), kafka-consumer-groups script supports consumer-group manually set offset(such as `--to-earliest`/`--to-latest`/`--to-offset`). Offical kafka-java client also support this feature by providing `auto.offset.reset` param.

It seems kafka-go doesn't support this feature as readme says:

![readme](https://user-images.githubusercontent.com/24546717/64667586-decd0980-d48c-11e9-9e0e-086020cc1cc6.png)

In some cases, one topic has mutiple consumer group, new consumer group want to consume the message from zero(earliest offset).

**Comment by tetafro** [comment]
> ... we wouldn't know which partition should be reset

@stevevls is it a bad idea to set offset to all available partitions of the topic?

**Comment by stevevls** [comment]
@tetafro It really depends on the use case.  There are some cases where one might want to wipe a consumer group entirely and reset to a particular state.  However, you could also imagine cases where an API client might to reset specific partitions (e.g. rebuilding data for a particular shard where the sharding scheme is based on message keys and their associated partition).  Since there's ambiguity in `Reader.SetOffset`, we take the safe approach which is to disallow the function for consumer groups and then provide lower-level primitives so that the API client can take an appropriate action based on their use case.

We do have issue #150 where we're tracking a wishlist for breaking API changes in the next major revision of kafka-go (currently unscheduled).  Consumer group support was added well after the `Reader` API had been solidified and released, so there are some rough edges since we have to maintain backward compatibility.  Feel free to add to the issue! 😄

**Comment by tetafro** [comment]
@stevevls thanks for your explanation. Can you take a look at my code? It gets all topic partitions and resets offset for them (the second part is taken from your example above). I spent some time looking for methods that can give me what I need, maybe I missed something. For the sake of simplicity the code doesn't use goroutins and always takes only first broker.

https://gist.github.com/tetafro/d46ca64e30b1a60b162ffe25ddef89e1

**Comment by stevevls** [comment]
Hi @tetafro.  The code looks good to me.  Have you had a chance to try it out yet?  My one advice is that you will want to be careful that this code is the only member of the consumer group (i.e. all your other consumers are shut down).  Otherwise, you could have a race if other consumers are processing messages and committing offsets because they could overwrite the offsets set by your program.

**Comment by tetafro** [comment]
> Have you had a chance to try it out yet?

Yep. It works.

> you will want to be careful that this code is the only member of the consumer group

Yes, I understand that. I use it as a local debugging tool when I want to check messages in kafka.

**Comment by stevevls** [comment]
Great...glad that worked!
