### ISSUE TITLE
 the kafka reader is reading before the first offset 

### ISSUE THREAD

**Issue by sureshbvn** [segmentio/kafka-go#365]
**Describe the bug**
I have setup where where have 64 partitions for the topic. 

We have 64 individual consumers. 16 processes and 4 go routines in each process. 
The producer produces at an avg of 200k objects per 15 minute interval. 

The kafka topic has a retention set to 1 day. 
We currently have a lag. (Consumer is not as fast a producer.) 

We see this error in our logs. 

 "the kafka reader is reading before the first offset for partition 12 of topic name skipping from offset 756242808 to 756253125 (10317 messages)"

After this the reader stops reading the messages.

**Kafka Version**
0.11

**Additional context**
We have messages larger than 1MB. We increased the kafka broker configuration. (max_bytes to 5MB). The max bytes of reader config is also updated accordingly.

The producer has no compression code enabled.

**Comment by wsx66848** [comment]
I also encountered the same problem.any solution?

**Comment by stevevls** [comment]
Greetings @sureshbvn and @wsx66848.  If your producers are consistently producing more messages than your consumers can process, eventually you'll run into this problem.  We currently take a safe approach in this case, which is to require the operator to intervene.  What kind of behavior are you hoping to see instead?

**Comment by ut0mt8** [comment]
I don't understand. You mean that the consumer can stop consume if the lag is too important ?

**Comment by stevevls** [comment]
Yup.  Imagine a case where you have a topic whose retention policy is 1 hour.  Now say that you have a producer that is producing 3M messages per hour and a consumer that can only consume 2M messages per hour.  If you were to start off with an empty topic, you would observe the following:

|  Hour  | Min Topic Offset  | Max Topic Offset   | Consumer Offset   |
|---|---|---|---|
|   0 |  0  | 0   | 0   |  
|  1  | 0  | 3M   | 2M   |   
|  2  | 3M  |  6M  | 4M   |
| 3 | 6M | 9M | 6M |
| 4 | 9M | 12M | 8 M (out of range!) | 

So sometime between hour 3 and 4, the consumer would no longer be able to keep reading messages because its offset will fall below the minimum offset retained by the broker.

**Comment by ut0mt8** [comment]
In hour 4 the consumer cannot consume because he want to read something that didn't exist anymore on the broker ok. My question is when you decide to stop consuming ?

Because if you decide earlier it's false in my opinion.
First because you assume that the trafic grows monolithically.
Also you assume all the message have the same message consume time average, that can be completely false (for example we have lot of pattern where a consumer skip most of the message, and only process some of them, and guess what it depend of the time of the day)/
And also we can add consumers or rebalance partition to speed up things.

So for me this is not the role of the consumer/client library to compute this kind of lag, consumer just consume until the end, or if it cannot. No lag calculation. This is upper logic that must reside in the application.

But maybe I completely mis understand this behaviour.

**Comment by wsx66848** [comment]
hello@stevevls nice to hear your reply.In my case, the host machine was powered off two days ago and my retention policy is 1 day.So when the machine is powered on, the last commit offset of the consumer group fall below the first offset of the partition(Sorry, my English isn't very good).And the debugger tells me the message and it seems like the consumer will skip the nonexistent message and read from the first offset.But in truth the consumer stop reading messages.Because every 30 minutes the debugger tells me the same thing.Here is the debug message.
19:59:38 the kafka reader is reading before the first offset for partition 0 of topic, skipping from
 offset 1372286754 to 1372753154 (466400 messages)
20:29:38 the kafka reader is reading before the first offset for partition 0 of topic, skipping from
 offset 1372753154 to 1373187054 (433900 messages)
20:59:38 the kafka reader is reading before the first offset for partition 0 of topic, skipping from
 offset 1373187054 to 1373606954 (419900 messages)
..... and so on.I just don't understand why the consumer stop read the message other than  read from the first offset.My consumer can process the messages produced by producer.Sorry again for my poor English

**Comment by stevevls** [comment]
Hello again.  Are you still having trouble with this issue?  If so, probably the best thing to do would be to increase the retention policy.  It sounds like kafka-go is operating as expected.  Thanks!

**Comment by sureshbvn** [comment]
Increasing the retention policy did not help. The consumption is being stopped. So unless we restart the process, the consumption does not resume.

**Comment by ut0mt8** [comment]
> Hello again. Are you still having trouble with this issue? If so, probably the best thing to do would be to increase the retention policy. It sounds like kafka-go is operating as expected. Thanks!

I didn't agree or at least the discussion above is very unclear. kafka libraries should not make any guess if there are messages to consume in the future. Messages can be consummed or no, meaning there are on brokers or not. If kafka-go don't have logic client side so this is ok, and maybe all this discussion is unrelevant.

**Comment by baconalot** [comment]
Who said it guesses anything. If you look at the code, you see that it fetches the first and last offset from the topic/partion on the broker. If the consumergroup offset is below the first offset on the broker it throws that error. No guessing involved here. The solution to your problem is to consume faster so it keeps up with the producer.

**Comment by sureshbvn** [comment]
we stopped using this library and moved to confluent kafka go client

Suresh
