### ISSUE TITLE
Incorrect type of `FirstOffset`

### ISSUE THREAD

**Issue by anandsinghkunwar** [segmentio/kafka-go#367]
**Describe the bug**
`FirstOffset` should be of type `int64` instead of `int` in `reader.go`. 

Demo: https://play.golang.org/p/c2j73lApIOW

**Comment by achille-roussel** [comment]
Hello @anandsinghkunwar, thanks for reporting the issue!

The constant are currently untyped, which means they can be used in expressions of any integer type. For example, both these expressions are valid:
```go
var x int

if x == kafka.FirstOffset {
    ...
}
```
```go
var x int64

if x == kafka.FirstOffset {
    ...
}
```
In the example you shared, a temporary variable is created to be passed as an `interface{}` to the `fmt.Printf` function. Go defaults to the `int` type for untyped integer literals, which is why your example seem to say that the type of `kafka.FirstOffset` is `int`.

The actual issue here is we have inconsistency between the types of `LastOffset` and `FirstOffset`, one is a `int64` typed constant, the other is untyped.

**Comment by anandsinghkunwar** [comment]
I understand, from what I understood `LastOffset` wasn't untyped but was `int64`, however `FirstOffset`. However in parts of the code where offset is used, for instance the `reader` part, it assumed that offset is `int64`. Hence `LastOffset` needed to be explicitly typed.
