### ISSUE TITLE
RetentionTime default should be 0

### ISSUE THREAD

**Issue by sneko** [segmentio/kafka-go#393]
Hi,

Currently the default RetentionTime for ConsumerGroup is 24 hours:
https://github.com/segmentio/kafka-go/blob/master/consumergroup.go#L51-L53

By taking a look at Sarama you can see this to 0. I think it's a better way if it would be 0.

![image](https://user-images.githubusercontent.com/8195958/71926761-52112e80-3194-11ea-93f5-97deec3d7fa5.png)

In my case, I set `offsets.retention.minutes` on the brokers so all offsets are kept for a long period. But didn't know the `kafka-go` could override this behavior. Some of my consumers got crazy by restarting from the beginning, and made some "mess" in my data 😢 .

Maybe I'm wrong it would be the better default case, any thought welcome 👍 

Thank you,

**Comment by sneko** [comment]
When you are aware of it that's fine... but it remains ambiguous for people adopting your lib.

cc @stevevls @achille-roussel

**Comment by achille-roussel** [comment]
Thanks for reporting the issue @sneko !

@stevevls what do you think about changing the default to not override the server settings, it seems like there is no way to do this currently.

**Comment by stevevls** [comment]
That seems reasonable to me.

I just did a little reading, and it looks like in Kafka < 2.0, the default for `offsets.retention.minutes` is 24 hours.  They increased it to 7 days in 2.0.  See [this KIP]( https://cwiki.apache.org/confluence/display/KAFKA/KIP-186%3A+Increase+offsets+retention+default+to+7+days).

The main case I can think of where a user could experience "odd" behavior is if they are using kafka-go's default but have `offsets.retention.minutes` configured on their cluster to <24h.  I think that's probably okay, though, since changing that setting on the broker side signals intention.
