### ISSUE TITLE
ReadPartitions shouldn't be a struct type defined on Client

### ISSUE THREAD

**Issue by bharatnc** [segmentio/kafka-go#403]
Hi:

To just read all the partitions that are available for a given kafka topic, right now I need to do this:

```golang
	conn, _ := kafka.DialLeader(context.Background(), "tcp", "kafka:9092", "my-topic", 0)
	parts, err := conn.ReadPartitions("my-topic")
	if err != nil {
		panic(err)
	}

```
It doesn't look intuitive to me that I need to specify a random partition number while initializing the client for me to able to get all the partitions. Also in the `ReadPartitions` implementation, I see that c.partition is not actually used anywhere inside the method itself to get a list of all Partitions. 

https://github.com/segmentio/kafka-go/blob/master/conn.go#L958

Should we do something similar to Sarama which is actually quite intuitive?

```golang
c.consumer, err = sarama.NewConsumerFromClient(c.client)
	if err != nil {
		panic(err)
	}
	
	allPartitions, err := c.consumer.Partitions("my-topic")
	if err != nil {
		panic(err)
	}
```
As far as I have seen segmentio kafka doesn't provide any convenient method to do just this.

**Comment by stevevls** [comment]
Hi @bharatnc.  

For your use case, you can use either the `kafka.Dial` or `kafka.DialContext` function, neither of which require the topic or partition number.

Generally speaking, the `kafka.Conn` type provides lower level functionality.  In some cases, it's necessary that a connection be made to a particular broker (produce and fetch requests need to be connected to the partition leader, consumer groups need to connect to the coordinator, etc.).  That's why we have the `DialLeader` function.  For getting topic metadata, though, it doesn't matter which broker you connect to, so the `Dial` function perfectly fine.

**Comment by bharatnc** [comment]
Sure makes sense, thank you @stevevls . I will try that out.
