### ISSUE TITLE
How should I mock consumer and producer written using segmentio?

### ISSUE THREAD

**Issue by aditi6622** [segmentio/kafka-go#421]
I need to mock consumer and producer which are written using segment io library. Please help me.

**Comment by achille-roussel** [comment]
Hello @aditi6622!

We don't have a solution in the package for mocking the kafka readers and writers at this time. You could declare interfaces that mirror the APIs of the reader and writer, and use these to replace the underlying implementation if needed (this is a common Go idiom).

Let me know if that information is useful.

**Comment by vikasorchestral** [comment]
do you have any example?

**Comment by achille-roussel** [comment]
This is more of a generic Go question than one specific to kafka-go; for example, if you wanted to declare an interface that was implemented by `kafka.Reader` and allowed consuming messages, you could write this:

```go
type KafkaReader interface {
  FetchMessage(ctx context.Context) (kafka.Message, error)
  CommitMessages(ctx context.Context, msgs ...kafka.Message) error
}
```

Methods with the same signatures exist on the `kafka.Reader` type, so it satisfies this interface. You can then use this interface in your program and either use a mock implementation, or use `kafka.Reader` when needed.

I hope this was useful. I will close the issue since the original question was answered, feel free to reopen if further discussion is needed.
