### ISSUE TITLE
Consumer is stuck, when facing a message with unsupported compression

### ISSUE THREAD

**Issue by rsteff** [segmentio/kafka-go#448]
**Describe the bug**
I have a service which does not support gzip compressed messages.
When (falsely) consuming a gzip compressed message the reader throws an error that is catched.
However, the message is consumed over and over again throwing an error.
It looks like the reader breaks off the consuming and always starts at the old offset again.
(See https://github.com/segmentio/kafka-go/blob/master/reader.go#L1272 and
https://github.com/segmentio/kafka-go/blob/master/reader.go#L719)
When sending another non compressed message it can be consumed, but afterwards the old gzip compressed message is consumed again and again.

**Kafka Version**
2.4.0

**To Reproduce**
```
func (d *kafkaConsumer) Run() {
	for {
		ctx := context.Background()
		m, err := d.commandReader.ReadMessage(ctx)
		d.healthy = err == nil
		if err != nil {
			logrus.WithError(err).Error("Error while receiving message")
			continue
		}
               // handleMessage(m)
        }
}
```

**Expected behavior**
It should be possible to consume messages after an unsupported message. Maybe by internally increasing the offset properly.

**Comment by achille-roussel** [comment]
Hello @rsteff, thanks for raising!

Would you be able to describe how you've generated an invalid message?

Blocking on a message which cannot be decoded can be the desired behavior in some cases, because it could otherwise result in data loss if the messages are simply skipped by the consumer, so if we do make a change it should probably be opt-in to avoid changing the default behavior.

Were you able to work around the issue when you imported the compression packages?

**Comment by dominicbarnes** [comment]
I'm closing this ticket due to a lack of response, please follow up with the requested information if you are still experiencing this issue.
