### ISSUE TITLE
kafka.NewReader Consumer GroupID in Loop

### ISSUE THREAD

**Issue by jeffotoni** [segmentio/kafka-go#454]
Guys, I had to reread messages if an error occurs when communicating with one of our services, that is, I don't do CommitMessages when the error occurs and I go back to the first loop starting the whole kafka.NewReader process.
Is there another way to implement this situation?

In my ReaderConfig the GroupID is defined because I need to read the Msg only once by this consumer when successfully communicating with our service.

I know we can use Dead-letter Topic, but that is not the case there.

The implementation below works.

```go
for {
		reader := kafkaNewReader(host, topic, grupo_id)
		ctx := context.Background()
		for {
			msg, err := reader.FetchMessage(ctx)
			err = MyService(msg) 
			if err != nil {
					println("Error: reprocess the message.. Waiting..")
					reader.Close()
					break
			}
		} 
		println("committing....")
		reader.CommitMessages(ctx, msg)
	}

**Comment by achille-roussel** [comment]
Hello @jeffotoni!

The solution you describe sounds fine to me, do you have specific concerns about it?

If you're looking to acquire finer grain control over the interactions with the consumer group, you may want to look at using the `kafka.ConsumerGroup` API directly instead of the reader (which is a wrapper around it).

Let me know if this is helpful.

**Comment by jeffotoni** [comment]
I'm keeping it this way man, if there is an error in my process / job it does not release the message always returning at the same offset and I never release this message is slower but it is what I can solve.

**Comment by achille-roussel** [comment]
I'm glad it's working for you 👍
