### ISSUE TITLE
Why is it slow to get  the first  messages ?

### ISSUE THREAD

**Issue by chen-ABC** [segmentio/kafka-go#505]
kafka version: 2.1   kafka-go:0.3.5

```
kafkaReader := kafka.NewReader(kafka.ReaderConfig{
    Brokers:   []string{"localhost:9092"},
    Topic:     "topic-A",
    Partition: 0,
})
for {
logs.Info(time.Now())  
msg, _ := kafkaReader.ReadMessage(context.Background())   
logs.Info(time.Now())  
logs.Info("part:0, msg:%s, offset:%d", string(msg.Value), msg.Offset)  
}
```
log:
The first message takes 10 seconds
![image](https://user-images.githubusercontent.com/30097790/92676260-c7508700-f353-11ea-87a0-18358522a718.png)

**Comment by stevevls** [comment]
Hi @chen-ABC.  Since you are not setting `MinBytes` or `MaxBytes` on your reader config, they are both set to the default of 1 MB.  That means your fetch request will block until there is 1 MB of data available.  The default values are applied here:

https://github.com/segmentio/kafka-go/blob/ff55eccb31e57f6b7982a444be71015991dbc64c/reader.go#L552-L558

I reviewed the documentation, and I think it could be improved to better describe the default behavior.  Thanks!

**Comment by chen-ABC** [comment]
thanks, it is useful
