### ISSUE TITLE
Reader Stats().Lag always returns 0

### ISSUE THREAD

**Issue by husentoding** [segmentio/kafka-go#508]
**Describe the bug**
Reader Stats().Lag always returns 0

**Kafka Version**
To be added later

**To Reproduce**
```
	rConfig := kafkago.ReaderConfig{
		Brokers:               k.connection,
		Topic:                 topic,
		GroupID:			   group,
		MaxWait:               100 * time.Millisecond,
		WatchPartitionChanges: true,
		ErrorLogger:           k.consumerLogger,
	}
```
```
	for {
		ctx := context.Background()
		msg, err := rc.reader.FetchMessage(ctx)
		if err != nil {
			log.Errorln("Failed to Fetch Data from Kafka. Error: ", err)
			continue
		}
		fmt.Println(rc.reader.Stats().Lag)
	}
```

**Comment by stevevls** [comment]
Hi @husentoding.

This may be kind of surprising, but `Lag` will always be zero when using a consumer group.  It has to do with the fact that the `kafka.Reader` originally only consumed from a single partition.  As such, `Lag` only reports a single `int64`.    Consumer group support was added quite a while later, but by then the signature for `Lag` was locked.  In the case where you're consuming from multiple partitions, though, it doesn't make sense to return a single number...a map of partition to lag would be more appropriate.

Since the code is behaving as expected, I've removed the `bug` label, but I've added the documentation and enhancement labels in case someone has time to open a PR to either improve the docs or to add new functionality to report the lag on multiple partitions.

Thanks!

**Comment by DevOpsFlux** [comment]
OKay~. I understood the part I was curious about.

------------------------------------------------------------
r := kafka.NewReader(kafka.ReaderConfig{ .... }

iReadLag, err := r.ReadLag(ctx)
if err != nil { fmt.Println("- iReadLag : ", iReadLag) }
fmt.Println("- r.Lag() : ", r.Lag()) 
fmt.Println("- r.Stats().Lag           : ", r.Stats().Lag)

------------------------------------------------------------
- iReadLag :  0
- r.Lag() : -1
- r.Stats().Lag  : 0
- iReadLag :  0
- r.Lag() : -1
- r.Stats().Lag  : 0
- iReadLag :  0
- r.Lag() : -1
- r.Stats().Lag  : 0
- iReadLag :  0
- r.Lag() : -1
- r.Stats().Lag  : 0
------------------------------------------------------------
$ kafka-consumer-groups --bootstrap-server kafka:9092 --group test01 --describe

GROUP       TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG 
test01      my-topic        0          436             439             3   
GROUP       TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG 
test01      my-topic        0          436             442             6      
GROUP       TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG 
test01      my-topic        0          436             445             9      
GROUP       TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG 
test01      my-topic        0          445             446             1

**Comment by rhansen2** [comment]
There's no built in way to get consumer group lag from the kafka.Reader. 

Closing this issue as I believe the original question has been answered.
