### ISSUE TITLE
Writer.RequiredAcks does not make any improvement in delivery-latency of kafka-message

### ISSUE THREAD

**Issue by aleksey-kurmanov** [segmentio/kafka-go#554]
Hi SegmentIO-Team!

The default delivery-latency using current kafka-driver is very high (about several seconds and up to 30 seconds in multiple kafka-partitions). In order to decrease it we decided to use `RequireNone(0)` for `Writer.RequiredAcks` and also use `Writer.BatchSize = 1` and `Writer.BatchBytes = 1`. But the duration of delivery-latency is quite the same - several seconds. We did not have stats from real environments yet, but at my local - quite no effect of such improvement.

Could you please suggest me what I'm doing wrong or what else should we do to decrease the delivery-latency of kafka-message.

Thanks in advance!
Aleksey.

**Comment by godwhoa** [comment]
Are you able to reproduce this locally? If so, small snippet + local kafka setup info would be nice. Want to take a jab at it, if it is a bug.

**Comment by aleksey-kurmanov** [comment]
I will try to reproduce it on your code-base. I doubt that it makes sense to send a portion of our project to you. Give me some time - I will thinks how to do it better in your `examples` folder...

**Comment by godwhoa** [comment]
@aleksey-kurmanov Out of curiosity, how are you measuring the "duration of delivery-latency"?

**Comment by achille-roussel** [comment]
Hello @aleksey-kurmanov!

I would recommend using one of the lower-level `kafka.Client` or `kafka.Conn` types if you are aiming to achieve low latency. The `kafka.Writer` type is optimized for throughput in streaming use cases, it implements batching of messages and therefore adds delays to the write path.

I will close due to lack of recent activity on this issue, but feel free to reopen if this demands further attention.
