### ISSUE TITLE
Have the same default values as the official client

### ISSUE THREAD

**Issue by godwhoa** [segmentio/kafka-go#557]
**Describe the solution you'd like**
Have the same default values as the official Kafka Client library.
Eg. kafka-go by default configures MaxWait time to 10s where as the official and many other clients default to 500ms.
This leads to a lot of questions like "why isn't kafka-go not behaving like library X?" which can be avoided.

**Supporting documentation**
https://github.com/segmentio/kafka-go/blob/v0.4.8/reader.go#L561
https://kafka.apache.org/documentation/#fetch.max.wait.ms
https://github.com/segmentio/kafka-go/blob/v0.4.8/reader.go#L557
https://kafka.apache.org/documentation/#fetch.min.bytes

**Comment by achille-roussel** [comment]
Hello @godwhoa, thanks for starting this discussion! (and for your contributions to the other issues).

We've historically been reluctant to changing defaults because these could easily cause production outages by implicitly modifying values that programs may depend on.

You make a good point that we're also creating confusion and increasing development cost by diverting from the defaults that kafka documents.

I'd be open to making the two changes you suggest at the condition that we provide thorough documentation on what the historical values used to be, and why we are changing them, possibly adding a note to the README, etc...

Would you be able to submit a pull request with these updates?

**Comment by godwhoa** [comment]
@achille-roussel Thanks for responding. I'd be happy to make a PR with those changes.

**Comment by achille-roussel** [comment]
Hello @godwhoa, just wanted to check whether you were still interested in submitting a PR to address this issue?

**Comment by godwhoa** [comment]
@achille-roussel Sadly no. You may close the issue if you want.

**Comment by achille-roussel** [comment]
Alright, feel free to reopen if needed in the future 👍
