### ISSUE TITLE
optimization to share reader when reading multiple partitions from the same broker

### ISSUE THREAD

**Issue by savaki** [segmentio/kafka-go#57]
consider allowing (*reader) to read from multiple partitions simultaneous.

Consider the following use case.  3 brokers, 1 topic with with 6 partitions.  In this scenario at least 2 readers are reading from the same broker albeit from separate topics.  It seems like this places unnecessary load on the brokers and could be resolved by allowing a reader to read from more than one partition.

**Comment by achille-roussel** [comment]
Yep, I've been thinking about this kind of optimizations. It's a trade off to make, because sharing a single TCP connection could result in worst consumer performance because there is no way to interleave parts of a response in the kafka protocol, the reader can send multiple concurrent requests and the correlation ID allows matching the response (because they can be out of order), but once a response is received it has to be read in full before the next response can be read. Short responses would be blocked on larger ones, plus there are potential lower-level bottlenecks when sharing TCP connections, like head-of-line blocking.

In the end, topics/partitions are very isolated resources in a kafka system, carrying fetch requests for multiple topic/partitions on the same connection may result in more harm than good.

Are you observing issues on kafka brokers due to having too many open connections?

**Comment by savaki** [comment]
The main thing I've been noticing is the difference in load using kafka-go vs sarama go.  anecdotally, kafka-go appears to put a noticeably higher amount of cpu pressure on the brokers than sarama did.  It's one of the areas I was meaning to look more closely into.

**Comment by achille-roussel** [comment]
Do you think it could be due to opening/closing connections to manage consumer groups, committing messages, etc... ?

I think we have greater opportunities for improvements there than batching fetches on a single connection (since those stay open for as long as possible, once established the overhead of a connection is pretty low).

**Comment by savaki** [comment]
Possibly.  I've already made some of the optimizations.  Commits for example, share a common Conn.  I might try and experiment with what happens if I reuse the heartbeat connection.

**Comment by savaki** [comment]
I'll close this for now until I've done more testing.
