### ISSUE TITLE
several Balancer issues

### ISSUE THREAD

**Issue by pierrre** [segmentio/kafka-go#581]
I was looking at the implementations of the Balancers and noticedseveral possible bugs.
https://github.com/segmentio/kafka-go/blob/f4ae85751b01b56c47362004ca9d0edb60ce5e36/balancer.go#L1

`Hash` doesn't use the values inside the slice `partitions`.
It's not doing something like `return partitions[idx]`.
I'm not sure, but it's probably wrong.
That's certainly why there is this condition:
```
	if partition < 0 {
		partition = -partition
	}
```

`Hash` and `Murmur2Balancer` are doing this check `msg.Key == nil`.
They should probably do `len(msg.Key) == 0` like `CRC32Balancer`.
An empty slice is not necessarily nil.

`LeastBytes` has a `mutex    sync.Mutex` field that is not used.
So it's not thread/concurrent safe.

**Comment by stevevls** [comment]
Thanks for the report @pierrre.

Some of the code you flagged looks odd in Go, but we've made sure that these balancers are interoperable with the Java and librdkafka libraries as they are considered to be the reference implementations for a Kafka client.

> Hash doesn't use the values inside the slice partitions.
It's not doing something like return partitions[idx].
I'm not sure, but it's probably wrong.
That's certainly why there is this condition:

>	if partition < 0 {
		partition = -partition
	}

In Java, the hash code is a signed integer (this differs from Go, where hash codes are unsigned).  When the sign bit is set, the partition is simply converted to a positive number by flipping it.  We've recreated this logic in Go.  Also, the hash code maps to an absolute partition number, so it's not necessary to index into the `partitions` slice.

> Hash and Murmur2Balancer are doing this check msg.Key == nil.
They should probably do len(msg.Key) == 0 like CRC32Balancer.
An empty slice is not necessarily nil.

In Java, nil and empty slices have different meanings and are given different treatment.  If we don't do the same, then our balancers will not be compatible.

> LeastBytes has a mutex sync.Mutex field that is not used.
So it's not thread/concurrent safe.

It looks like this field as added in 0.4, but you are correct that it is unused.  It looks like the mutex might have been intended to protect the `counters` field in the `Balance` function.  @achille-roussel does that sound right?

**Comment by pierrre** [comment]
OK, I didn't read full this comment
> we do not get the same result as sarama

So I guess it makes sense to keep the same algorithm, in order to keep th compatibility with Sarama.


However I'm pretty sure this code is never executed:
```go
	if partition < 0 {
		partition = -partition
	}
```


> Also, the hash code maps to an absolute partition number, so it's not necessary to index into the partitions slice.

I'm not really a Kafka expert.
What are the values we receive in `partitions ...int` ?
Is it really OK to return a partition ID that was not provided from the `partitions` slice ?
Why are all the balancers returning a value from `partitions`, except the `Hash` implementation ?


About nil/empty slices, is it really OK to have a different behavior in `Hash`/`Murmur2Balancer` vs `CRC32Balancer` ?

**Comment by stevevls** [comment]
> However I'm pretty sure this code is never executed

It definitely is.  If you want to convince yourself, remove that block of code and run the unit tests. 😄   That code is important because when you convert the `uint32` hash code to a signed `int32`, the number will be interpreted as negative if the most significant bit is set (see https://en.wikipedia.org/wiki/Two%27s_complement).

> What are the values we receive in partitions ...int ?

It is the partition IDs, which will be in the range of `[0,numPartitions)`.  I'm not sure, but I do not think the slice is guaranteed to be sorted.

> Is it really OK to return a partition ID that was not provided from the partitions slice ?

Certain partitioners require an absolute value while others are not sensitive to it.  Take for example a round robin partitioner--the only guarantee it makes is that it cycles through the partitions, but it is not sensitive to the order in which it cycles.  The hash partitioner on the other hand guarantees that a key always maps to the same partition across all producers and across process restarts.  For that reason, it computes the partition explicitly.  Provided that the partition is in the range `[0,numPartitions)`, this is a safe thing to do.

> Why are all the balancers returning a value from partitions, except the Hash implementation ?

See above!

> About nil/empty slices, is it really OK to have a different behavior in Hash/Murmur2Balancer vs CRC32Balancer ?

This is also for parity with the Java and librdkafka implementations.  They're not consistent in their treatment of `nil` versus empty. 😄

**Comment by pierrre** [comment]
ok, I understand, thank you

**Comment by dominicbarnes** [comment]
It sounds like the conversation here cleared up the confusion, so I'm going to close the ticket. Feel free to re-open if you feel like there is still an issue here to address.
