### ISSUE TITLE
How to set dialer using kafka.Writer?

### ISSUE THREAD

**Issue by girafferiel** [segmentio/kafka-go#644]
It's written in the docs that to set SASL dialer, we can use this:
```golang
mechanism, err := scram.Mechanism(scram.SHA512, "username", "password")
if err != nil {
    panic(err)
}

dialer := &kafka.Dialer{
    Timeout:       10 * time.Second,
    DualStack:     true,
    SASLMechanism: mechanism,
}

w := kafka.NewWriter(kafka.WriterConfig{
	Brokers: []string{"localhost:9093"},
	Topic:   "topic-A",
	Balancer: &kafka.Hash{},
	Dialer:   dialer,
})
```

But how to set it using &kafka.Writer ? Thanks

**Comment by achille-roussel** [comment]
Hello @girafferiel, thanks for opening the issue.

I've changed the label from "bug" to "documentation" because it does not appear that there are any issues with the implementation, but rather this is a problem with the documentation referring to deprecated APIs.

Moving forward, the `kafka.Transport` type is intended to replace the use of kafka connections (internally and externally) and hosts the SASL configuration.

You may configure a custom transport on the `kafka.Writer` prior to using it, otherwise `kafka.DefaultTransport` is used instead.

If you are able to, we will welcome an update of the outdated documentation as well 👍 

Let me know if this was helpful.

References:
- https://pkg.go.dev/github.com/segmentio/kafka-go#Transport
- https://pkg.go.dev/github.com/segmentio/kafka-go#Writer

**Comment by girafferiel** [comment]
```
writer := kafka.Writer{
		Addr:         kafka.TCP(brokers...),
		Balancer:     &kafka.LeastBytes{},
		BatchTimeout: 1 * time.Millisecond,
	}
```
I initiate a writer without a topic so that I can write messages with diff topics later, but I keep getting this error:
kafka.(*Writer).WriteMessages: cannot create a kafka writer with an empty topic"

**Comment by girafferiel** [comment]
nvm the fix was i need to upgrade the library... thanks very much
