### ISSUE TITLE
writer attempts to create thousands of new connections against the broker during traffic spikes

### ISSUE THREAD

**Issue by AndierZ** [segmentio/kafka-go#645]
**Describe the bug**
Either with Async=false or true, if you drop a lot of messages to WriteMessages, because newWriteBatch fires off a new batch on a new goroutine every time ([here](https://github.com/segmentio/kafka-go/blob/master/writer.go#L690)), it could eventually want to create a new connection if the conn pool runs out of available connections. When this happens you'll see  hundreds or thousands of dials within a few seconds, completely overwhelming the broker. 

**Kafka Version**
What version(s) of Kafka are you testing against?
2.1

**To Reproduce**
Try dropping about 10k - 20k messages per second for a minute, couple hundred bytes per message. Default batch size 100. Batch time out single digit ms.

**Expected behavior**
Either more configuration or expose more methods that the user can customize behavior. Ideally I'd like to specify max number of connections allowed, and have messages queue up if that number is reached. Equally importantly, it'd be nice to have more control over batching. For example, when the traffic is light, I'd like to flush the batches quickly to achieve better latency. But when traffic spikes, I'd like to wait and send more messages per batch to achieve better throughput. 

**Additional context**

**Comment by achille-roussel** [comment]
Hello @AndierZ, thanks for reporting the issue.

The `kafka.Transport` type does not apply a limit to the maximum number of open connections, and as a result the behavior you describe is possible.

This is an enhancement that we could make, in a similar with that the standard `net/http` package introduced `MaxConnsPerHost` in Go 1.11, we could limit the number of connections per broker and hang on submitting requests instead of opening new connections when the limit is reached.

If you have time to work on this improvement, we always welcome external contributions.

> Equally importantly, it'd be nice to have more control over batching. For example, when the traffic is light, I'd like to flush the batches quickly to achieve better latency. But when traffic spikes, I'd like to wait and send more messages per batch to achieve better throughput.

Would you mind opening a separate issue to track this discussion?

**Comment by dalianzhu** [comment]
i have the same issue,I write thousands of messages every second, and create thousands connections. Eventually the system will cut off all connections because of security issues.
what should i do?Thanks for help

**Comment by vtolstov** [comment]
@achille-roussel do you have plans to limit max conns ?

**Comment by achille-roussel** [comment]
No immediate plans but this seems like a useful change.

@vtolstov @dalianzhu 
Would one of you be able to contribute a change to add this feature in the `kafka.Transport` type?

**Comment by vtolstov** [comment]
i dont have spare time for this, mostly i see that this package not useful to write async commit logic with consumer group (via NewConsumerGroup and handling partitions by own to allow parallel processing).
If you don't plan to improve this stuff and provide  reader that  able to return multiple messages at once for different partitions i'm need to switch to https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo library. because it has more useful funcs for async communication like https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#Client.CommitOffsetsSync

**Comment by achille-roussel** [comment]
I'm glad you found a tool that suits your needs, if you would like to see those features added to kafka-go in the future feel free to reopen the discussion or send a pull request to contribute the changes 👍
