### ISSUE TITLE
adding poll interval  to consumer

### ISSUE THREAD

**Issue by yoka791** [segmentio/kafka-go#658]
Hi,
I was wondering if it's possible to consume messages in a pool interval.  
I mean that I want my consumer to read the messages every x seconds, and then handling them.
Is it possible?
I noticed that there is a configuration `ReadBackoffMin` and `ReadBackoffMax` but it seems like the "sleep" is applied only for error/retry, but in most cases there won't be any sleep. am I right?

**Comment by achille-roussel** [comment]
Hello @yoka791, thanks for starting the discussion.

This is not a behavior that is currently available in kafka-go; you could achieve it by setting a large MinBytes and MaxWait on the reader configuration, but it may return earlier than MaxWait if enough data gets produced to the partitions.

May I ask why you're interested in having this added to kafka-go rather than being implemented by the application? It does not seem too complex to pause using a `time.Ticker` before each call to fetch messages.
