### ISSUE TITLE
why not triger all batches when all messsage are added?

### ISSUE THREAD

**Issue by b1ackhuang** [segmentio/kafka-go#694]
when we use api WriteMessages to batch write message, message will be sent when batch are reached or batch became full. but when we write singal message which isn't reach batch size, so we must wait for batch time reaching.

why not triger all batches when all messsage are added?

**Comment by achille-roussel** [comment]
Hello @b1ackhuang 

The `WriteMessages` API on a `kafka.Writer` is designed to facilitate streaming and parallel processing use cases where the application wants to process messages individually and delegate batch aggregation to the Kafka client layer.

If this is not a desirable behavior for your use case you may want to look at using `kafka.(*Client).Produce`, or `kafka.(*Conn).WriteMessages` which will give you access to lower level Kafka APIs.

Despite coming late, I hope this answer was useful. I'll close due to the age of the issue, but feel free to reopen if this needs further discussion.
