### ISSUE TITLE
How I can stop or sleep Consumer after I geting no message in golang

### ISSUE THREAD

**Issue by patilvikas0205** [segmentio/kafka-go#696]

**Comment by achille-roussel** [comment]
Hello @patilvikas0205, thanks for asking!

I am not sure how to fully interpret your question without more context on the issue. Would you be able to share a code snippet highlighting what you are trying to achieve? Or maybe describe the issue in more details?

**Comment by patilvikas0205** [comment]
I have write code for kafka consumer anf producer and now i have to write mock or unit test on producer and consumer

**Comment by achille-roussel** [comment]
Apologies for not following up on this issue earlier: testing is a broad problem space and the right answer will likely depend on details that are specific to your use case.

That being said, here are strategies that you should use with kafk-go:
* use a Kafka cluster for the test, we do this in kafka-go with docker-compose for example, but you could also use hosted solutions like AWS MSK for that purpose. This approach would give you stronger guarantees that the code is tested "end-to-end" as it would be interacting with an actual cluster over network connections.
* provide a custom implementation of the `kafka.RoundTripper` interface. This would probably be the closest to a "mock", however there will be limitations at this stage due to ongoing work on kafka-go (e.g. the `kafka.Reader` type does not use `kafka.RoundTripper` yet).

I'll close due to the age of the issue but I hope the answer was useful anyways, feel free to reopen if this needs further discussion.
