### ISSUE TITLE
admin API access

### ISSUE THREAD

**Issue by alexec** [segmentio/kafka-go#705]
I'm writing some software that needs to calculate the approximate pending messages (by summing across offsets for the consumer group). I'm using Sarama for this today, but want to try out kafka-go instead because after testing, I've seen Sarama loose messages when the client is shutdown.

https://github.com/argoproj-labs/argo-dataflow/blob/39cd13afff9d5aa460c6411cca6035a97cbf566c/runner/sidecar/sources.go#L179

Is there an equivalent to `NewClusterAdmin`?

**Comment by achille-roussel** [comment]
Hello @alexec, thanks for starting this conversation!

First, I apologize for the delayed response, the contributor that the issue was assigned to had left the maintainer group and this did not get reassigned properly.

Regarding your question, I believe this is already possible to implement with kafka-go, the [`kafka.(*Client).ListOffsets`](https://pkg.go.dev/github.com/segmentio/kafka-go#Client.ListOffsets) API should allow you to compute this information.

Let me know if this response was useful or whether you believe kafka-go could offer more support for this use case.

**Comment by achille-roussel** [comment]
I'm going to close this issue assuming the last message provided an answer, feel free to reopen if this requires further discussion.
