### ISSUE TITLE
Bug: CommitMessages errors when committing without groupID for partition consumers

### ISSUE THREAD

**Issue by jsteenb2** [segmentio/kafka-go#72]
Description:

setting up a reader to consume on a topic:

```go
cfg := kafka.ReaderConfig{
				Brokers:   cfg.Kafka.Brokers,
				Topic:     partition.Topic,
				Partition: partition.ID,
				MaxBytes:  10e6,
			}

r := kafka.NewReader(cfg)
```

Then after fetching messages and then going to commit like so: 

```go
// procesing of message
if err := p.R.CommitMessages(ctx, window...); err != nil {
   log.Println(err) // always gets error here
}
```

What I get is the following error message: `not available when GroupID is set`

I did not set a GroupId in my cfg. Upon further inspection it seems that inside the `CommitMessage()` method, the first line of the body is the following:

```go
if !r.useConsumerGroup() { // line 1215 of reader.go
	return errNotAvailable
}
```

When I remove the `!` from the `if` it runs as desired.  Is this expected behavior? Is the err message wrong or is it the `if` statement that is wrong?

**Comment by achille-roussel** [comment]
Hello @jsteenb2 

From what you describe I believe this is the expected behavior.

`CommitMessages` only needs to be called when you're using consumer groups (by setting a `GroupID`), if you address a partition directly there is no offset management done on the kafka side, and therefore you don't need to explicitly declare which messages you have consumed. However, you likely have to use some form of storage to track the last offset that you've consumed (like a database or a file).

If your intent was to have your consumer be part of a group with offsets managed by kafka then you should set a `GroupID` in your configuration, in that case consumers negotiate partition assignment and you don't need to explicitly tell them which partition to consume from.

Let me know if this helps, or if you're running into other issues.

**Comment by jsteenb2** [comment]
thanks for the quick response @achille-roussel, i'm trying to create seperate readers for each partition in my use case. When I go commit for a single partition I get the `not available when GroupID is set` error msg, which threw me off as to what CommitMessages could be used for. Is the commit message suppose to read `not available when GroupID is not set`?

Little confused as to where that CommitMessages method can be used as it reads

**Comment by achille-roussel** [comment]
Basically when you use consumer groups (by setting a `GroupID`), your consumer is potentially managing multiple offsets for multiple topics and partitions. It needs to inform kafka of which messages it has processed so kafka can move the offsets forward. This is what `CommitMessages` is used for.

Without calling `CommitMessages`, the next time you create a reader (by restarting your program for example), it would read the same messages again as kafka wouldn't know that the messages were successfully handled.

If you want to do direct partition addressing and you have no need for consumer groups, don't call CommitMessages. You just configure your reader to start at the offset you want to consume from and read messages 😉

**Comment by jsteenb2** [comment]
I read you, no pun intended ;-). Thanks for the input. I'm still a bit perplexed by the error message though.  It seems to contradict if my english is correct?

`not available when GroupID is set` <-- current message, says unavailable when GroupID is set
&
`not available when GroupID is unset` <-- says available when GroupID is set

🤷‍♀️ 

the current message makes it sounds opposite to the intended behavior you described above. Might be a nitpick on my end, but ate up a chunk of my time. I'd hate to see others get confused by it as well.

BTW, this library has proven to be much more dependable than any other go kafka library out there. GREAT STUFF! 👍

**Comment by achille-roussel** [comment]
Ah! I see what you mean, I misunderstood.

Yep it seems inaccurate, would you mind sending a PR to give a better error message?

**Comment by jsteenb2** [comment]
sure thing, PR submitted 👍

**Comment by ImDoubD-datazip** [comment]
@achille-roussel Hey, I want to sync data from kafka as source to a given destination. Now i want to create separate readers for  multiple partitions, also one thing i do it to set offset manually as required. But the problem is I need to commit the messages read manually as per my wish, when I want. Basically, until and unless the message is not written to prescribed destination until then I don't want to commit, I want to commit message to kafka only after writing the message to destination after reading and processing from the kafka. How can I do this?

This above I am doing because when using group id, I am not able to set offset as per my wish. As written in docs, it can only be either FirstOffset or LastOffset. I want to set offset manually as per my wish whichever I want. 

Use case: offset of message which is already written at destination, i persist that in a state file and want to set reading of message starting from offset + 1 (persisted in state) for that partition. 

Also can you tell me, if using only partitions in reader with no group id, when exactly message commit action takes place to kafka?
