### ISSUE TITLE
WriteMessages function will block the goroutine while topic not exist and  client no permission to create topic

### ISSUE THREAD

**Issue by cridly** [segmentio/kafka-go#806]
**Describe the bug**
When the topic does not exist and the client does not have permission to create the topic, the WriteMessages function will block indefinitely.

**Kafka Version**
v1.1.0

**To Reproduce**
Steps to reproduce the behavior.  Bonus points for a code sample.
1) Topic does not exist
2) Client does not have permission to create topic
3) Topics are automatically created when the client writes a message
4) The goroutine will be blocked permanently without returning an error
5) This problem exists in v0.4.23 and later versions

**Expected behavior**
WriteMessages function will not block the goroutine and get errors return while client no permission to create topic

**Comment by 1000Delta** [comment]
I got the same problem, I need to set WriteMessages ctx WithTimeout so that can cancel and return error TopicOrPartitionNotFound.

I review the code about `WriteMessages`, I see it call `RoundTripper.RountTrip`, and the param req set `AllowAutoTopicCreation: true`, this caused the block indefinitely.

https://github.com/segmentio/kafka-go/blob/8dfb9153020e2a9c65fbcc0d1e6564192511a87f/writer.go#L704-L707

Caused by this option, client will to refresh metadata to try to get expect topics from broker, so it call `connPool.refreshMetadata`:

https://github.com/segmentio/kafka-go/blob/8dfb9153020e2a9c65fbcc0d1e6564192511a87f/transport.go#L418-L420

In this method, it send `event` to `p.wake` to force update metadata, After receive the notify, it will check the topics that want to create whether in updated topic list, and wait time between `minBackoff` to `maxBackoff`, until **find all expect topics** or **ctx cancel** or **ctx Error not nil**:

https://github.com/segmentio/kafka-go/blob/8dfb9153020e2a9c65fbcc0d1e6564192511a87f/transport.go#L436-L474

I think kafka-go should expose the option of `AllowAutoTopicCreation` or automatic check the config of auto create topic from kafka broker?
