### ISSUE TITLE
Producing first message with the AWS_IAM_MSK authentication take a very long time

### ISSUE THREAD

**Issue by HeedoKang** [segmentio/kafka-go#829]
Producing first message with the AWS_IAM_MSK authentication take a very long time. As a result of measuring with my code, it takes an average of 2-2.5sec. The below is my code and is there anything that I'm missing or wrong?

```golang
	config := kafka.WriterConfig{}

	config.Brokers = brokers
	config.RequiredAcks = int(kafka.RequireAll)
	config.BatchTimeout = 5 * time.Millisecond
	
	// SASL_IAM auth set
	creds := credentials.NewEnvCredentials()

	iamMechanism := &aws_msk_iam.Mechanism{
		Signer:   sigv4.NewSigner(creds),
		Region:   region,
		SignTime: time.Now(),
		Expiry: 24 * time.Hour,
	}

	config.Dialer = &kafka.Dialer {
		TLS:		   &tls.Config{},
		DualStack:     false,
		SASLMechanism: iamMechanism,
	}

	// create producer and ready for use
	producer = kafka.NewWriter(config)
	err = sendInitMessage()
```

**Comment by dominicbarnes** [comment]
I believe there are at least 2 sources of latency creating the behavior you are describing.

First, the `Writer` doesn't necessarily flush every message immediately, as internal batching occurs. The default behavior is to flush batches once per second, or after 1,048,576 bytes are reached, whichever comes first. Since you are only publishing 1 message, you're likely waiting for the 1s batch timeout.

Second, there is also some latency from the brokers acknowledging the message, which by default requires all brokers to acknowledge each message. Depending on your cluster and network configuration, this could likely explain additional latency.

The `Writer` is built for concurrent, high-volume streams of data, which benefits greatly from batching as it reduces overhead with round-trips to the Kafka brokers. As such, low-volume situations like this don't really present a representative picture for most streaming applications.

You can adjust the configuration to suit this use-case by lowering the `BatchBytes` configuration or `BatchTimeout` to flush batches more frequently, but depending on your actual production use-cases this likely won't be necessary.

Hopefully this addresses your concerns, please follow up on the ticket if you have any additional questions.

**Comment by HeedoKang** [comment]
@dominicbarnes Thanks for your reply. But I've already set `BatchTimeout` to 5 milliseconds.

The case is only produced when I enable TLS encryption and IAM authentication.
When the options (TLS encryption and authentication) are disabled, producing first message takes only a few hundreds milliseconds. 

However, when I enable the options, producing a first message takes about more than 2.5 seconds (after the first message, it only takes about a few hundred milliseconds to write a message.)

Is there any other advice for me?
