### ISSUE TITLE
All consumers experiencing fetching error due bad consumers

### ISSUE THREAD

**Issue by alan-delrio** [segmentio/kafka-go#842]
**Describe the bug** >> This is more a question rather than bug. I googled and unfortunately couldn't find someone asking the same. I would not surprised if errors are broadcasted to all consumers. Rebalancing errors are.

Good consumers (1,2) get impacted by bad consumers (3,4,5) errors . Good consumers get error messages generated by bad consumers also during message reading. 

All consumers use SASLMechanism authentication with kafka.Dialer 
All consumers use same credentials (user/password)
All consumers use the same consumer group name: "ED209"
Each consumer tries to get messages from different topic, no overlap. 
We know good consumers have access to the topics they try to connect.
We realized bad consumers have NO access to the topics they try to connect.
Consumer 1 uses confluent Java library v?
Consumer 2-5 use segmentio kafka-go v0.4.22

Good Consumer 1 dials successfully. then starts fetching messages from topic "A"
Good Consumer 2 dials successfully, then starts fetching messages from topic "B"

Bad Consumer 3-5 dial successfully, but get error due not having access to topics "C","D","E":
```
[29] Topic Authorization Failed: the client is not authorized to access the requested topic
```
When bad consumers face this error they restart themselves (Containerized service\restart+1)

Good Consumer 1,2 start experiencing same error and stop consuming:
```
[29] Topic Authorization Failed: the client is not authorized to access the requested topic
```

We thought good consumers 1,2 would not experience any error due bad consumers 3-5
Question, is this expected behavior?_ 

**Kafka Version**
Confluent 6.1.2
Kafka 2.7.0

**To Reproduce**
_Use same account to connect to different topics using same consumer group
Grant access to only 2/5 topics
Try to consume to all topic with one consumer each_

**Expected behavior**
_2 Consumers stay trying to fetch messages without error due no access to topic associated to other 3 consumers_

**Additional context**
Confluent kafka platform internal team blames segmentio library for the errors impacting all consumers
I'm being forced to switch to https://github.com/confluentinc/confluent-kafka-go/

I think platform team is not being impartial, they show a lot of distrust again segmentio kafka library because it is not the official one associated to confluent. I'm reporting this so that I can hear from segmentio team and provide feedback, I suspect it can be a known confluent behavior or simply something on the broker side regardless of the library. Trying to use confluent library and reproduce behavior.

I like segmentio library, I hope I can hear from you so that we can have arguments to keep it

**Comment by alan-delrio** [comment]
Replaced bad consumers 3-5 with github.com/segmentio/kafka-go v0.4.22 no errors on good consumer 1-2
I wished I could have continue using segmentio so that I could continue using a static build : /

**Comment by achille-roussel** [comment]
Hello @alan-delrio, thanks for reporting the issue!

The use case you describe sounds like something we definitely haven't had a need to solve for before, so I would say it's not unexpected that it does not exhibit the ideal behavior here.

What I assume might be happening are the errors cause the consumers to leave the consumer group, which triggers a rebalance and assign the unauthorized partitions to the remaining consumers, which in turn fail to read from the topics. The reason this might be happening is because when using a single consumer group, partitions are distributed for all topics to consumers taking part in the group.

Documentation on how the reference clients behave is hard to find, so it's possible that we have diverged from librdkafka or the Java client in those edge case scenarios.

As for next steps, I am curious to better understand your use case, maybe a different approach could temporarily work around the issue (for example, having a different consumer group for each topic?). If you are able to, we would also welcome a contribution to fix the issue, otherwise the kafka-go maintainer team will review and decide what next steps we can take.

**Comment by alan-delrio** [comment]
As far as I know topic+group combination is used like a unique key for offset management and balancing purposes. Using a different combination should keep other consumers unaware of errors. Not sure if segmentio clients are sending requests or metadata that cause kafka to broadcast error to all consumers using the same account or consumer group. Let me change the consumer group on the bad actors and see what happens to provide more clues

**Comment by alan-delrio** [comment]
I guess you guys are still the number one on the golang landscape
https://github.com/edenhill/librdkafka/issues/3223

**Comment by alan-delrio** [comment]
Added kafka version:
Confluent 6.1.2
Kafka 2.7.0

**Comment by achille-roussel** [comment]
Hello @alan-delrio, I wanted to check back on this issue and ask if you were able to verify whether using different consumer groups was preventing the issue from occuring.

Let me know!

**Comment by alan-delrio** [comment]
Unfortunately I couldn't invest more time, I was forced to migrate to confluent library and we have a tight schedule. While using confluent-kafka-go I notices 2 things more:

- I couldn't re-use segmentio consumers groups. I had to change it to a new one
- Reported bad behavior is not present using using conflient-kafka-go / librdkafka

I miss my cross platform build ; (
