### ISSUE TITLE
Any timeline on when v1 will be out?

### ISSUE THREAD

**Issue by abjsaha** [segmentio/kafka-go#96]
I am looking for a solution like kafka-go, but don't want to invest in it right now as there isn't a stable version of it available yet. Is there a timeline for v1?

**Comment by achille-roussel** [comment]
So far we have made no breaking changes since we first started working on kafka-go about a year ago, and the goal is to keep it this way, I'd consider this API stable.

That being said, we can work on reviewing the ongoing work and figure out when would be the right time to tag a v1 of the project. At first sight it would probably require https://github.com/segmentio/kafka-go/pull/80 to be completed and merged to make kafka-go compatible with a wide range of kafka versions, other than that I don't foresee any changes on the API or the implementation that would break builds or behaviors of existing programs.
