### ISSUE TITLE
memory leak while using async writer

### ISSUE THREAD

**Issue by Khanzadeh-AH** [segmentio/kafka-go#980]
**Describe the bug**

> I was producing message using a few number of goroutines. My network bandwidth is not sufficient enough and it can't keep up with message production. My memory usage keeps growing by time till all messages are in it. I think messages are first stored in memory and then shipped.

**Kafka Version**

> kafka version = 2.3.0 (Commit:fc1aaa116b661c8a)
> kafka-go version =  v0.4.34

**To Reproduce**

> Here is how I'm using async kafka writer:

```go
writer := &kafka.Writer{
    Addr:                   kafka.TCP(config.KafkaServer),
    Topic:                  config.Topic,
    AllowAutoTopicCreation: true,
    Balancer:               &kafka.LeastBytes{},
    Async:                  true,
    RequiredAcks:           kafka.RequiredAcks(1),
}

writer.WriteMessages(context.Background(),
    kafka.Message{
    Value: []byte(message),
},
```

**Expected Behavior**

> I expect the messages to be stored in memory and then sent to network considering memory size.

**Observed Behavior**

> Memory usage keeps growing by time, and does not fall before the process is finished executing.

**Comment by dominicbarnes** [comment]
When you use the async writer, the messages will be buffered into memory by design. By definition, kafka-go will attempt to deliver all the messages you send to it asynchronously, but we currently put no limits on how many messages we accept at this time, leaving this up to the application to define. This mode also reduces your ability to handle errors, since context will likely be lost when delivering messages in this way.

Most use-cases should probably produce messages synchronously instead, as it will give you much more control over how much memory your application will use by waiting for messages to be delivered and acknowledged by the brokers before allowing your program to continue. (and returning an error explicitly if that fails for any reason)

**Comment by qingyunha** [comment]
I also encounter this problem. The process RSS has increased to 40G. I think this may be caused by the unlimited  batchQueue https://github.com/segmentio/kafka-go/blob/eba9cae7fd57401a8078f6f25bc00cb753cd4f42/writer.go#L938

**Comment by qingyunha** [comment]
https://kafka.apache.org/33/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html 
> The buffer.memory controls the total amount of memory available to the producer for buffering. If records are sent faster than they can be transmitted to the server then this buffer space will be exhausted. When the buffer space is exhausted additional send calls will block. The threshold for time to block is determined by max.block.ms after which it throws a TimeoutException.
