### ISSUE TITLE
Is there a way to markOffsets for a kafka reader consumer group

### ISSUE THREAD

**Issue by ekeric13** [segmentio/kafka-go#983]
I have used sarama before as a kafka and the way you consume data in that library is you set auto-commit to commit offsets every x seconds. And then as you read data from a topic you update it's offset in order to read more, and after a message has been acked you mark that the offset is available for auto-committing:

https://pkg.go.dev/github.com/Shopify/sarama#ConsumerGroupSession
https://github.com/Shopify/sarama/blob/main/examples/consumergroup/main.go#L177-L195

Kafka-go exposes a `CommitInterval`:
https://pkg.go.dev/github.com/segmentio/kafka-go#ReaderConfig

But it seems that along with [FetchMessage](https://pkg.go.dev/github.com/segmentio/kafka-go#Reader.FetchMessage), to avoid explicitly committing the messages. But if you have a failed ack or don't ack before the commitInterval lapses, won't you be committed unprocessed data? The solution seems to be having some sort of MarkOffset function but I cannot find one.

**Comment by dominicbarnes** [comment]
I think there may be a slight misunderstanding about how `CommitInterval` works on a `Reader`. The interval defines how often we commit messages, at which point we only commit the messages that are marked as committed by the application.

When using the `ReadMessage` API, each message is _marked_ for commit automatically upon receipt, so it will be committed to the broker on the next interval. Conversely, when using `FetchMessage` you must call `CommitMessages` in order to mark messages as ready for commit. Only after a message has been passed to `CommitMessages` and a commit interval passes will that message be committed to the broker as well.

Thus, if you need to ensure that messages are not committed until it has been successfully processed, use the `FetchMessage` and `CommitMessages` APIs.

**Comment by ekeric13** [comment]
So if `CommitInterval` is set to 0 ( the default). And you call `FetchMessage`, process your messages, and then call `CommitMessages` will they just be committed immediately? I am assuming they are from my usage.

So it sounds like if I set `CommitInterval` to 3 seconds, and then call `CommitMessages` on my processed messages I am essentially just marking records, which was my desired behavior... is that right?
